{
  "hash": "17ff42766b68cb0cbf2e3f07f926a523",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Partial and Semi-Partial Correlation Analysis with PRAMS 8 Data\"\nauthor: \"Barboza-Salerno\"\ndate: \"2026-01-27\"\nformat:\n  html:\n    toc: true\n    number-sections: false\n    theme: sandstone\nbibliography: references.bib\ncsl: apa-with-abstract.csl  \n---\n\n## Dataset Description\n\nThe **Pregnancy Risk Assessment Monitoring System (PRAMS) Phase 8** dataset collects data on maternal behaviors and experiences before, during, and after pregnancy. The sample is drawn from birth certificate records across multiple jurisdictions, covering 81% of U.S. live births. I would provide the link to the data but of course it is now gone due to the censorship happening with our government currently, which has substantial implications for the reproductive health of women and other persons regardless of their pregnancy status.\n\nThis analysis uses the data from Kansas. These data were used because I wanted to focus on associations between ACEs, maternal education, parenting stress, and intimate partner violence. Each state administers its own modules, and for some reason Kansas asked these. If you would like to read a summary of the findings from these data, check out [this website](kdhe.ks.gov/ArchiveCenter/ViewFile/Item/2841).\n\n## Introduction\n\nUnderstanding how early-life adversity, maternal education, and stress during pregnancy interact is crucial for maternal and child health research. This analysis examines the relationships between **Adverse Childhood Experiences (ACEs)**, **Stress During Pregnancy (STRESS)**, and **Maternal education (Meduc)** using **partial and semi-partial correlation** techniques. The goal is to determine whether maternal education during pregnancy influences stress levels beyond what can be explained by prior adverse experiences (ACEs).\n\n## Research Question\n\n-   Does **Maternal Education** predict **Stress During Pregnancy** after controlling for **Adverse Childhood Experiences (ACEs)?**\n-  Does **dverse Childhood Experiences (ACEs)** predict **Stress During Pregnancy** after controlling for **Maternal Education?**\n-   How does the relationship between **ACEs and Stress** change when we control for education in both variables (Partial Correlation) vs. when we remove the effect of education only from Stress (Semi-Partial Correlation)?\n\n### Data and Variables\n\n[Click here](data/KSPRAMS_SUB_COR.csv) for the dataset used in the analysis.\n\n[Click here](slides/MLR/correlate.R) for the R script for which this example is based.\n\nThe table below provides an overview of the key variables used in this analysis:\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'knitr' was built under R version 4.3.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: 'xfun::attr()' is deprecated.\nUse 'xfun::attr2()' instead.\nSee help(\"Deprecated\")\nWarning: 'xfun::attr()' is deprecated.\nUse 'xfun::attr2()' instead.\nSee help(\"Deprecated\")\n```\n\n\n:::\n\n::: {.cell-output-display}\n\n\nTable: PRAMS Phase 8 Variable Descriptions\n\n|Variable_Name |Label                                             |Recodes                                 |\n|:-------------|:-------------------------------------------------|:---------------------------------------|\n|NEED_TRAN     |Access to Basic Needs - Affordable Transportation |Material Hardship                       |\n|NEED_FOOD     |Basic Needs - Food Insecurity                     |Material Hardship                       |\n|NEED_SHOUS    |Basic Needs - Safe Housing                        |Material Hardship                       |\n|NEED_CHOUS    |Basic Needs - Consistent Housing                  |Material Hardship                       |\n|NEED_CROWD    |Basic Needs - Crowded Housing                     |Material Hardship                       |\n|NEED_UTIL     |Basic Needs - Utilities                           |Material Hardship                       |\n|NEED_PHON     |Basic Needs - Phone Access                        |Material Hardship                       |\n|NEED_OTH      |Basic Needs - Other Unmet Needs                   |Material Hardship                       |\n|HDP_SAF       |Partner Threatened Safety                         |Intimate Partner Violence               |\n|HDP_ANGR      |Partner Anger/Threats                             |Intimate Partner Violence               |\n|HDP_CTRL      |Partner Control of Activities                     |Intimate Partner Violence               |\n|HDP_SEX       |Partner Forced Sexual Activity                    |Intimate Partner Violence               |\n|STRS_FM3      |Close Family Member Hospitalized                  |Social Stressor                         |\n|STRS_DV3      |Divorce or Separation                             |Social Stressor                         |\n|STRS_MOV      |Moved to a New Address                            |Social Stressor                         |\n|STRSHOME      |Homelessness                                      |Social Stressor                         |\n|STRS_JOB      |Partner Lost Job                                  |Social Stressor                         |\n|STRS_WRK      |Lost Job Despite Wanting to Work                  |Social Stressor                         |\n|STRS_PAY      |Cut in Work Hours or Pay                          |Social Stressor                         |\n|STRS_AWY      |Separated from Partner Due to Deployment/Travel   |Social Stressor                         |\n|STRS_ARG      |Frequent Arguments with Partner                   |Social Stressor                         |\n|STRS_PG       |Partner Did Not Want Pregnancy                    |Social Stressor                         |\n|STRS_BIL      |Problems Paying Rent/Mortgage                     |Social Stressor                         |\n|STRS_DRG      |Close Person Had a Drug or Alcohol Problem        |Social Stressor                         |\n|STRS_DH3      |Close Person Died                                 |Adverse Childhood Experiences           |\n|CDHD_DVRC     |Parent or Guardian Divorced/Separated             |Adverse Childhood Experiences           |\n|CDHD_HOUS     |Moved Due to Rent/Mortgage Issues                 |Adverse Childhood Experiences           |\n|CDHD_FOOD     |Went Hungry Due to Food Insecurity                |Adverse Childhood Experiences           |\n|CDHD_JAIL     |Parent or Guardian Involved in Legal System       |Adverse Childhood Experiences           |\n|CDHD_SUBS     |Parent or Guardian Had Substance Use Issues       |Adverse Childhood Experiences           |\n|CDHD_FSTR     |Experience in Foster Care                         |Adverse Childhood Experiences           |\n|CIG_1TRI      |Cigarettes Smoked Daily - 1st Trimester           |Cigarettes Smoked Daily - 1st Trimester |\n|MAT_ED        |Maternal Years of Education                       |Maternal Education                      |\n\n\n:::\n:::\n\n\n## Explanation of Correlation Types\n\n### Correlation\n\n**Definition:** Measures the direct (linear) relationship between two variables without controlling for other influences.\n\n-   **What does it ask?** \"How strongly are two variables associated?\" \"When one variable increases, does the other also increase (positive correlation), decrease (negative correlation), or are the variables not linearly related?\"\n\n-   **Why does this matter?**\n\n1.  *Identifies basic associations*: Helps determine whether two variables have a relationship worth further investigation.\n\n2.  *Guides hypothesis development*: Provides an initial understanding before applying more complex statistical techniques like partial correlation or regression.\n\n3.  *Does not imply causation*: A strong correlation does not mean one variable causes changes in the other; it simply indicates they move together.\n\n-   **Example Interpretation:** If ACEs and Stress During Pregnancy have a positive correlation, it suggests that individuals with higher adverse childhood experiences tend to experience more stress during pregnancy. However, other factors (e.g., education, income) could be influencing this relationship.\n\n-   Positive values indicate a direct relationship (when one increases, the other also increases).\n\n-   Negative values indicate an inverse relationship (when one increases, the other decreases).\n\n-   Values closer to 0 suggest a weak or no linear association between the variables. *This DOES NOT mean* that no relationship exists.\n\n### Partial Correlation\n\n**Definition:** Measures the direct relationship between two variables while controlling for the effect of a third variable.\n\n-   **What does it ask?** \"What is the association between **Maternal Education** and **Stress During Pregnancy**, after removing the effect of **ACEs** from both?\"\\\n\n-   **Why does this matter?** If the correlation remains significant, this suggests that education independently contributes to stress beyond what can be explained by early-life adversity.\n\n### Semi-Partial (Part) Correlation\n\n**Definition:** Measures the relationship between two variables while controlling for a third variable’s effect on just one of them.\n\n-   **What does it ask?** \"What is the association between **Maternal Education** and **Stress During Pregnancy**, after removing the effect of **ACEs** only from **Stress During Pregnancy**?\"\n\n-   **Why does this matter?** If the relationship weakens, it suggests that ACEs account for some of the variance in how education affects stress. Another way to think about this is that ACEs partly explain how education effects stress. And, yet another 'connect-the-dots' moment is that tf the relationship weakens, then ACEs [mediate](09-mediation.qmd) some of the observed effects of education on stress\n\n## Data Import and Preprocessing\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(ppcor) # For partial and semi-partial correlation\n\n# Load dataset\ndf <- read.csv(\"data/KSPRAMS_SUB_COR.csv\")\n\n# Select relevant columns\ndata_subset <- df %>% \n  dplyr::select(ACEs, STRESS, Meduc) %>% \n  na.omit()\n\n# Check summary statistics\nsummary(data_subset)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      ACEs           STRESS           Meduc      \n Min.   :0.000   Min.   : 0.000   Min.   :1.000  \n 1st Qu.:0.000   1st Qu.: 0.000   1st Qu.:3.000  \n Median :0.000   Median : 1.000   Median :4.000  \n Mean   :1.043   Mean   : 1.892   Mean   :3.916  \n 3rd Qu.:2.000   3rd Qu.: 3.000   3rd Qu.:5.000  \n Max.   :6.000   Max.   :14.000   Max.   :5.000  \n```\n\n\n:::\n:::\n\n\n::: {.callout-warning}\nPlease pay particular attention to the handling of missing data in R. There are many ways to handle missing data with significant implications for your analysis. For some good guides to handling missing data in R see [How does R handle missing data](https://stats.oarc.ucla.edu/r/faq/how-does-r-handle-missing-values/) from UCLA and [Missing data tutorial in R](https://libguides.princeton.edu/R-Missingdata) from Princeton University.\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Compute Pearson correlation matrix\ncor_matrix <- cor(data_subset, method = \"pearson\")\n\n# Print correlation matrix\nprint(cor_matrix)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             ACEs     STRESS      Meduc\nACEs    1.0000000  0.3411429 -0.2399357\nSTRESS  0.3411429  1.0000000 -0.2105974\nMeduc  -0.2399357 -0.2105974  1.0000000\n```\n\n\n:::\n:::\n\n\n### **Computed Correlation Matrix**\n\nThe table below presents Pearson correlation coefficients between ACEs (Adverse Childhood Experiences), STRESS (Stress During Pregnancy), and Meduc (Maternal Education Level). Each correlation value ranges from -1 to 1.\n\nBelow is the **Pearson correlation matrix** for the selected variables:\n\n| Variable   | ACEs   | STRESS | Meduc  |\n|------------|--------|--------|--------|\n| **ACEs**   | 1.00   | 0.341  | -0.239 |\n| **STRESS** | 0.341  | 1.00   | -0.210 |\n| **Meduc**  | -0.239 | -0.210 | 1.00   |\n\n**Interpretation of Results:**\n\n1.  **ACEs and STRESS** ( r = 0.341 ):\n\n-   There is a **moderate positive correlation** between adverse childhood experiences and stress during pregnancy.\n-   This suggests that individuals who report more childhood adversity tend to experience higher stress levels during pregnancy.\n\n2.  **ACEs and Meduc** ( r = -0.239 ):\n\n-   There is a **moderate negative correlation** between ACEs and maternal education.\n-   This indicates that individuals with higher levels of childhood adversity tend to have **lower levels of educational attainment**.\n\n3.  **STRESS and Meduc** ( r = -0.210 ):\n\n-   A **moderate negative correlation** exists between stress and maternal education.\n-   This suggests that individuals with lower educational attainment tend to experience **higher stress levels** during pregnancy.\n\n------------------------------------------------------------------------\n\n#### Summary & Implications\n\nWomen with more Adverse Childhood Experiences (ACEs) tend to experience higher levels of stress during pregnancy and have lower education levels. Higher maternal education is linked to lower stress, potentially due to greater access to resources, stability, or support systems. This is important. When interpreting results, it is very important to go back to the original operationalization of the variables so we are on the same page. How is stress defined here? And, what may be some limitations both methodologicall and conceptually? Whereas we know this analysis is not causal, we can begin linking the results to some important policy implications See @barboza2020cognitive [here](static/1-s2.0-S0190740919311533-main.pdf) .\n\n## Compute Partial and Semi-Partial Correlations\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Compute Partial Correlation (controlling for ACEs)\npartial_corr <- pcor(data_subset)\nprint(\"Partial Correlation Matrix:\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Partial Correlation Matrix:\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(partial_corr$estimate)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             ACEs     STRESS      Meduc\nACEs    1.0000000  0.3062254 -0.1829213\nSTRESS  0.3062254  1.0000000 -0.1410824\nMeduc  -0.1829213 -0.1410824  1.0000000\n```\n\n\n:::\n\n```{.r .cell-code}\n# Compute Semi-Partial Correlation (controlling for ACEs only in STRESS)\nsemi_partial_corr <- spcor(data_subset)\nprint(\"Semi-Partial Correlation Matrix:\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Semi-Partial Correlation Matrix:\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(semi_partial_corr$estimate)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             ACEs     STRESS      Meduc\nACEs    1.0000000  0.2972802 -0.1719481\nSTRESS  0.2993577  1.0000000 -0.1326190\nMeduc  -0.1788189 -0.1369612  1.0000000\n```\n\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n## Correlation Analysis\n\nWe computed three types of correlation matrices:\n\n1.  **Zero-Order (Regular) Correlation**: The direct correlation between variables.\n2.  **Partial Correlation**: The correlation between two variables while controlling for a third variable (Meduc).\n3.  **Semi-Partial Correlation**: The correlation between two variables while controlling for a third variable’s influence on just one of them.\n\n## **Results and Interpretation**\n\n### **Regular (Zero-Order) Correlation** from above\n\n| Variable   | ACEs   | STRESS | Meduc  |\n|------------|--------|--------|--------|\n| **ACEs**   | 1.00   | 0.341  | -0.239 |\n| **STRESS** | 0.341  | 1.00   | -0.210 |\n| **Meduc**  | -0.239 | -0.210 | 1.00   |\n\n-   **ACEs and STRESS**: ( r = 0.341 ) → A **moderate positive correlation**, indicating that individuals with higher ACEs tend to experience higher stress levels during pregnancy.\n-   **ACEs and Meduc**: ( r = -0.239 ) → A **negative correlation**, suggesting that individuals with more childhood adversity tend to have lower educational attainment.\n-   **STRESS and Meduc**: ( r = -0.210 ) → A **negative correlation**, implying that lower maternal education is linked to higher stress.\n\n------------------------------------------------------------------------\n\n### **Partial Correlation**\n\n| Variable   | ACEs   | STRESS | Meduc  |\n|------------|--------|--------|--------|\n| **ACEs**   | 1.00   | 0.306  | -0.182 |\n| **STRESS** | 0.306  | 1.00   | -0.141 |\n| **Meduc**  | -0.182 | -0.141 | 1.00   |\n\n-   **ACEs and STRESS** controlling (partialing out) Meduc: ( r = 0.306 ) → The correlation remains positive but slightly decreases compared to the zero-order correlation ( r = 0.341 ), indicating that while education partly explains the relationship, ACEs still have a significant effect on stress.\n-   **ACEs and Meduc** controlling ACEs: ( r = -0.182 ) → The correlation between ACEs and education weakens slightly after controlling for stress.\n-   **STRESS and Meduc** controlling for STRESS: ( r = -0.141 ) → The relationship between stress and education is weaker when controlling for ACEs.\n\n### **Implication of Partial Correlation**\n\nBy controlling for maternal education, we isolate the direct effect of **ACEs on stress**. The reduction in correlation values suggests that education contributes to stress, but ACEs continue to have a **strong independent effect**.\n\n------------------------------------------------------------------------\n\n### **Semi-Partial Correlation (Controlling for Meduc Only in STRESS)**\n\n| Variable   | ACEs   | STRESS | Meduc  |\n|------------|--------|--------|--------|\n| **ACEs**   | 1.00   | 0.297  | -0.171 |\n| **STRESS** | 0.299  | 1.00   | -0.132 |\n| **Meduc**  | -0.178 | -0.136 | 1.00   |\n\n-   **ACEs and STRESS**: ( r = 0.297 ) → A slight decrease in the strength of the relationship compared to the partial correlation (( r = 0.306 )), meaning that education explains a small part of the ACEs-stress relationship. In other words, it's the correlation between ACEs and the part of STRESS that is independent of Meduc.\n-   **ACEs and Meduc**: ( r = -0.171 ) → The correlation weakens slightly after accounting for stress.\n-   **STRESS and Meduc**: ( r = -0.132 ) → A marginal decrease in the strength of the relationship.\n\n### **Implication of Semi-Partial Correlation**\n\nThe semi-partial correlations examine how **each independent variable uniquely contributes** to the dependent variable while removing the effect of the control variable **only from the dependent variable**. Since the values remain similar to the partial correlations, this suggests that **maternal education influences stress**, but ACEs still have an independent impact.\n\n------------------------------------------------------------------------\n\n## **Key Takeaways**\n\n1.  ACEs are a strong predictor of stress during pregnancy, even after controlling for maternal education.\n2.  Maternal education partially explains the relationship between ACEs and stress, but ACEs continue to have an independent effect.\n3.  Higher maternal education is associated with lower stress, but its effect is weaker when ACEs are accounted for.\n4.  The semi-partial correlation results confirm that maternal education plays a role, but ACEs have an independent impact on stress, highlighting the importance of addressing childhood adversity in maternal mental health interventions.\n\nThese results suggest that **public health interventions should target both early-life adversity (ACEs) and educational opportunities** to reduce stress during pregnancy, which may have long-term effects on maternal and child health outcomes.\n\n\n## Conclusion\n\nThis analysis demonstrates how **Maternal Education**, **Stress During Pregnancy**, and **ACEs** interact within a structured correlation framework. Using **partial and semi-partial correlations**, we disentangle the direct and indirect effects of early-life adversity on maternal stress, providing insights for interventions aimed at reducing stress-related health disparities. If ACEs remains a significant predictor of stress after controlling for education, interventions targeting early life adversity may help alleviate psychosocial stress during pregnancy, improving both maternal and child health outcomes.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}