% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  letterpaper,
  DIV=11,
  numbers=noendperiod]{scrartcl}

\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else  
    % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\setlength{\emergencystretch}{3em} % prevent overfull lines
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
% Make \paragraph and \subparagraph free-standing
\makeatletter
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}{
    \@ifstar
      \xxxParagraphStar
      \xxxParagraphNoStar
  }
  \newcommand{\xxxParagraphStar}[1]{\oldparagraph*{#1}\mbox{}}
  \newcommand{\xxxParagraphNoStar}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}{
    \@ifstar
      \xxxSubParagraphStar
      \xxxSubParagraphNoStar
  }
  \newcommand{\xxxSubParagraphStar}[1]{\oldsubparagraph*{#1}\mbox{}}
  \newcommand{\xxxSubParagraphNoStar}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
\makeatother

\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{241,243,245}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.40,0.45,0.13}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\BuiltInTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\ExtensionTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.28,0.35,0.67}{#1}}
\newcommand{\ImportTok}[1]{\textcolor[rgb]{0.00,0.46,0.62}{#1}}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.07,0.07,0.07}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}

\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother

\KOMAoption{captions}{tableheading}
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother

\usepackage{bookmark}

\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={Admissions Data Analysis},
  pdfauthor={Generated Report},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}


\title{Admissions Data Analysis}
\author{Generated Report}
\date{2025-02-09}

\begin{document}
\maketitle


\section{Introduction}\label{introduction}

This report analyzes \textbf{admissions data}, focusing on
\textbf{predicting SAT Math scores} using SAT Verbal scores and high
school class size. The analysis employs \textbf{linear regression
models}, correlation assessments, and visualizations to explore the
relationships between these variables.

\section{Load Necessary Libraries}\label{load-necessary-libraries}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(foreign)    }\CommentTok{\# For reading .sav files}
\FunctionTok{library}\NormalTok{(ggplot2)    }\CommentTok{\# For visualization}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Warning: package 'ggplot2' was built under R version 4.3.3
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(dplyr)      }\CommentTok{\# For data manipulation}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}

Attaching package: 'dplyr'
\end{verbatim}

\begin{verbatim}
The following objects are masked from 'package:stats':

    filter, lag
\end{verbatim}

\begin{verbatim}
The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(gtsummary)  }\CommentTok{\# For creating regression tables}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
#BlackLivesMatter
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(officer)    }\CommentTok{\# For exporting to Word}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Warning: package 'officer' was built under R version 4.3.3
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(flextable)  }\CommentTok{\# For table formatting}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}

Attaching package: 'flextable'
\end{verbatim}

\begin{verbatim}
The following objects are masked from 'package:gtsummary':

    as_flextable, continuous_summary
\end{verbatim}

\section{Load and Inspect Data}\label{load-and-inspect-data}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{admissions }\OtherTok{\textless{}{-}} \FunctionTok{read.spss}\NormalTok{(}\StringTok{"data/admissions.sav"}\NormalTok{, }\AttributeTok{to.data.frame =} \ConstantTok{TRUE}\NormalTok{)}
\FunctionTok{head}\NormalTok{(admissions) }\CommentTok{\# Display first few rows}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
  row_number paiddeposit scholarship_yes_no Type_of_scholarship_offered Female
1          7           1                  0                                  0
2         12           0                  0                                  0
3         19           1                  0                                  0
4         23           1                  0                                  0
5         25           0                  0                                  0
6         28           0                  0                                  1
             Race HS_rank HS_class_size HS_Quintile HS_CODE
1 white               190           281        4/5   392835
2 white               111           223        3/5   393655
3 white               109           371        2/5    51830
4 Asian                88           266        2/5   390527
5 white                NA            NA              390870
6 white                59           382        1/5   392655
                  HS_NAME SAT_math SAT_verbal ACT Honors_college_eligible
1 FRANKLIN_REGIONAL_SR_HI      620        560  NA                     no 
2 CENTRAL_CATHOLIC_HIGH_S      550        600  NA                     no 
3 WESTCHESTER_HIGH_SCHOOL      640        550  NA                     no 
4 CEDAR_CLIFF_HIGH_SCHOOL      620        520  NA                     no 
5 HOLY_GHOST_PREPARATORY       550        650  NA                     no 
6 PENN_MANOR_HIGH_SCHOOL       480        460  20                     no 
  distancefromPitt state Number_of_family_alumni father_alumni grand_alumni
1        14.228946    PA                       0             0            0
2         7.162134    PA                       0             0            0
3       232.363382    PA                       0             0            0
4       163.462296    PA                       0             0            0
5       261.534151    PA                       0             0            0
6       192.493359    PA                       0             0            0
  mother_alumni sibling_alumni step_parent_alumni other_family_alumni
1             0              0                  0                   0
2             0              0                  0                   0
3             0              0                  0                   0
4             0              0                  0                   0
5             0              0                  0                   0
6             0              0                  0                   0
  SAT_composite ACT_as_SAT Max_Test_Score Training from_PA      ZRE_1
1          1180         NA           1180        0       1  0.6224412
2          1150         NA           1150        0       1 -0.7729867
3          1190         NA           1190        0       1  0.9373749
4          1140         NA           1140        0       1  0.9339243
5          1200         NA           1200        0       1         NA
6           940        950            950        0       1 -1.0502366
       ZRE_2              alumniYN
1  0.6224412 Family is not an alum
2 -0.7729867 Family is not an alum
3  0.9373749 Family is not an alum
4  0.9339243 Family is not an alum
5         NA Family is not an alum
6 -1.0502366 Family is not an alum
\end{verbatim}

\section{Data Preprocessing}\label{data-preprocessing}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{admissions\_clean }\OtherTok{\textless{}{-}}\NormalTok{ admissions }\SpecialCharTok{\%\textgreater{}\%} 
\NormalTok{  dplyr}\SpecialCharTok{::}\FunctionTok{select}\NormalTok{(SAT\_math, SAT\_verbal, HS\_class\_size) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{na.omit}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\section{Simple Linear Regression: SAT Math \textasciitilde{} SAT
Verbal}\label{simple-linear-regression-sat-math-sat-verbal}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{simple\_model }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(SAT\_math }\SpecialCharTok{\textasciitilde{}}\NormalTok{ SAT\_verbal, }\AttributeTok{data =}\NormalTok{ admissions\_clean)}
\FunctionTok{summary}\NormalTok{(simple\_model) }\CommentTok{\# Regression summary}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}

Call:
lm(formula = SAT_math ~ SAT_verbal, data = admissions_clean)

Residuals:
     Min       1Q   Median       3Q      Max 
-168.125  -43.568   -1.667   41.119  188.462 

Coefficients:
             Estimate Std. Error t value Pr(>|t|)    
(Intercept) 329.24934   19.49133   16.89   <2e-16 ***
SAT_verbal    0.45572    0.03448   13.22   <2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 61.42 on 689 degrees of freedom
Multiple R-squared:  0.2023,    Adjusted R-squared:  0.2011 
F-statistic: 174.7 on 1 and 689 DF,  p-value: < 2.2e-16
\end{verbatim}

\subsubsection{Interpretation:}\label{interpretation}

\begin{itemize}
\tightlist
\item
  \textbf{SAT Verbal has a positive effect on SAT Math scores} (Estimate
  = 0.45572, p \textless{} 0.001).
\item
  \textbf{Model explains \textasciitilde20.2\% of variance in SAT Math
  scores} (Adjusted R² = 0.2011), meaning SAT Verbal alone is a moderate
  predictor.
\item
  \textbf{Residuals appear reasonably distributed}, suggesting no major
  violations of normality assumptions.
\end{itemize}

\section{Compute Fitted Values and
Residuals}\label{compute-fitted-values-and-residuals}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{admissions\_clean}\SpecialCharTok{$}\NormalTok{fitted\_simple }\OtherTok{\textless{}{-}} \FunctionTok{fitted}\NormalTok{(simple\_model)}
\NormalTok{admissions\_clean}\SpecialCharTok{$}\NormalTok{residuals\_simple }\OtherTok{\textless{}{-}} \FunctionTok{residuals}\NormalTok{(simple\_model)}
\end{Highlighting}
\end{Shaded}

\section{Compute Standardized Values}\label{compute-standardized-values}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{admissions\_clean}\SpecialCharTok{$}\NormalTok{std\_fitted\_simple }\OtherTok{\textless{}{-}} \FunctionTok{scale}\NormalTok{(admissions\_clean}\SpecialCharTok{$}\NormalTok{fitted\_simple)}
\NormalTok{admissions\_clean}\SpecialCharTok{$}\NormalTok{std\_residuals\_simple }\OtherTok{\textless{}{-}} \FunctionTok{scale}\NormalTok{(admissions\_clean}\SpecialCharTok{$}\NormalTok{residuals\_simple)}
\end{Highlighting}
\end{Shaded}

\section{Visualization: Residuals
vs.~Fitted}\label{visualization-residuals-vs.-fitted}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(admissions\_clean, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ std\_fitted\_simple, }\AttributeTok{y =}\NormalTok{ std\_residuals\_simple)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{color =} \StringTok{"blue"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_hline}\NormalTok{(}\AttributeTok{yintercept =} \DecValTok{0}\NormalTok{, }\AttributeTok{linetype =} \StringTok{"dashed"}\NormalTok{, }\AttributeTok{color =} \StringTok{"red"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Standardized Residuals vs. Standardized Fitted Values (Simple Model)"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Standardized Fitted Values"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Standardized Residuals"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{admissions_R_ex_files/figure-pdf/unnamed-chunk-7-1.pdf}}

\subsubsection{Interpretation:}\label{interpretation-1}

\begin{itemize}
\tightlist
\item
  \textbf{Residuals are fairly symmetrically distributed} around zero,
  suggesting the linear model is appropriate.
\item
  \textbf{No major patterns} in residuals indicate homoscedasticity.
\end{itemize}

\section{Histogram of Residuals}\label{histogram-of-residuals}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(admissions\_clean, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ residuals\_simple)) }\SpecialCharTok{+}
  \FunctionTok{geom\_histogram}\NormalTok{(}\AttributeTok{bins =} \DecValTok{30}\NormalTok{, }\AttributeTok{fill =} \StringTok{"lightblue"}\NormalTok{, }\AttributeTok{color =} \StringTok{"black"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Histogram of Residuals (Simple Model)"}\NormalTok{, }\AttributeTok{x =} \StringTok{"Residuals"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Frequency"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{admissions_R_ex_files/figure-pdf/unnamed-chunk-8-1.pdf}}

\subsubsection{Interpretation:}\label{interpretation-2}

\begin{itemize}
\tightlist
\item
  \textbf{Residuals follow a normal-like distribution}, supporting the
  assumption of normality.
\end{itemize}

\section{Correlation Analysis}\label{correlation-analysis}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cor}\NormalTok{(admissions\_clean[, }\FunctionTok{c}\NormalTok{(}\StringTok{"SAT\_math"}\NormalTok{, }\StringTok{"SAT\_verbal"}\NormalTok{, }\StringTok{"fitted\_simple"}\NormalTok{, }\StringTok{"residuals\_simple"}\NormalTok{)], }\AttributeTok{use =} \StringTok{"complete.obs"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
                  SAT_math    SAT_verbal fitted_simple residuals_simple
SAT_math         1.0000000  4.497305e-01  4.497305e-01     8.931643e-01
SAT_verbal       0.4497305  1.000000e+00  1.000000e+00    -5.014076e-16
fitted_simple    0.4497305  1.000000e+00  1.000000e+00    -1.828283e-15
residuals_simple 0.8931643 -5.014076e-16 -1.828283e-15     1.000000e+00
\end{verbatim}

\subsubsection{Interpretation:}\label{interpretation-3}

\begin{itemize}
\tightlist
\item
  \textbf{Strong positive correlation} between SAT Math and SAT Verbal
  (r ≈ 0.45).
\item
  \textbf{Fitted values highly correlate with SAT Verbal}, confirming
  its predictive power.
\end{itemize}

\section{Multiple Linear Regression: SAT Math \textasciitilde{} SAT
Verbal + HS Class
Size}\label{multiple-linear-regression-sat-math-sat-verbal-hs-class-size}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{multiple\_model }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(SAT\_math }\SpecialCharTok{\textasciitilde{}}\NormalTok{ SAT\_verbal }\SpecialCharTok{+}\NormalTok{ HS\_class\_size, }\AttributeTok{data =}\NormalTok{ admissions\_clean)}
\FunctionTok{summary}\NormalTok{(multiple\_model)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}

Call:
lm(formula = SAT_math ~ SAT_verbal + HS_class_size, data = admissions_clean)

Residuals:
     Min       1Q   Median       3Q      Max 
-165.924  -44.589   -1.418   40.825  197.261 

Coefficients:
               Estimate Std. Error t value Pr(>|t|)    
(Intercept)   314.14654   19.47735  16.129  < 2e-16 ***
SAT_verbal      0.44864    0.03401  13.192  < 2e-16 ***
HS_class_size   0.06030    0.01295   4.656 3.88e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 60.52 on 688 degrees of freedom
Multiple R-squared:  0.2266,    Adjusted R-squared:  0.2244 
F-statistic: 100.8 on 2 and 688 DF,  p-value: < 2.2e-16
\end{verbatim}

\subsubsection{Interpretation:}\label{interpretation-4}

\begin{itemize}
\tightlist
\item
  \textbf{HS Class Size has a small but significant positive effect}
  (Estimate = 0.06030, p \textless{} 0.001).
\item
  \textbf{Explained variance increases to 22.4\%}, showing a slight
  improvement over the simple model.
\end{itemize}

\section{Visualization of SAT Verbal
Effect}\label{visualization-of-sat-verbal-effect}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(admissions\_clean, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ SAT\_verbal, }\AttributeTok{y =}\NormalTok{ SAT\_math)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{method =} \StringTok{"lm"}\NormalTok{, }\AttributeTok{col =} \StringTok{"blue"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Effect of SAT Verbal on SAT Math"}\NormalTok{, }\AttributeTok{x =} \StringTok{"SAT Verbal"}\NormalTok{, }\AttributeTok{y =} \StringTok{"SAT Math"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
`geom_smooth()` using formula = 'y ~ x'
\end{verbatim}

\pandocbounded{\includegraphics[keepaspectratio]{admissions_R_ex_files/figure-pdf/unnamed-chunk-11-1.pdf}}

\section{Generate Regression Summary
Table}\label{generate-regression-summary-table}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mlr\_table }\OtherTok{\textless{}{-}}\NormalTok{ multiple\_model }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{tbl\_regression}\NormalTok{(}\AttributeTok{label =} \FunctionTok{list}\NormalTok{(}\AttributeTok{SAT\_verbal =} \StringTok{"SAT Verbal Score"}\NormalTok{, }\AttributeTok{HS\_class\_size =} \StringTok{"High School Class Size"}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{modify\_caption}\NormalTok{(}\StringTok{"Table 1: Multiple Linear Regression Results"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{add\_n}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\section{Save Table to Word}\label{save-table-to-word}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mlr\_flextable }\OtherTok{\textless{}{-}} \FunctionTok{as\_flex\_table}\NormalTok{(mlr\_table)}
\NormalTok{doc }\OtherTok{\textless{}{-}} \FunctionTok{read\_docx}\NormalTok{()}
\NormalTok{doc }\OtherTok{\textless{}{-}} \FunctionTok{body\_add\_flextable}\NormalTok{(doc, }\AttributeTok{value =}\NormalTok{ mlr\_flextable)}
\FunctionTok{print}\NormalTok{(doc, }\AttributeTok{target =} \StringTok{"MLR\_Results.docx"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\section{Conclusion}\label{conclusion}

\subsubsection{Key Findings:}\label{key-findings}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{SAT Verbal scores significantly predict SAT Math scores},
  explaining \textasciitilde20\% of the variance.
\item
  \textbf{Adding HS Class Size improves the model slightly}, raising the
  explained variance to 22.4\%.
\item
  \textbf{Both models suggest a linear relationship}, with residuals
  showing normality and no major violations.
\end{enumerate}

\subsubsection{Implications:}\label{implications}

\begin{itemize}
\tightlist
\item
  Schools aiming to improve SAT Math scores may focus on strengthening
  verbal skills.
\item
  Class size appears to play a small but relevant role in performance.
\item
  Further research could explore additional predictors (e.g.,
  socioeconomic factors, study habits).
\end{itemize}




\end{document}
