{
  "hash": "0f6ea907018ad94b3ee1e28cb997331e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Admissions Data Analysis\"\nauthor: \"Barboza-Salerno\"\ndate: \"2026-01-26\"\nformat:\n  html:\n    toc: true\n    number-sections: false\n    theme: sandstone\n---\n\n# Introduction\n\nThis code analyzes **admissions data**, focusing on **predicting SAT Math scores** using SAT Verbal scores and high school class size. The analysis employs **linear regression models**, including [simple linear regression](02-simple-regression.qmd), [multiple linear regression](03-multiple-regression.qmd), correlation assessments, and visualizations to explore the relationships between these variables.\n\nHere is the [admissions data](data/admissions.sav) and you can download the script to run in R [here](admissions_R_ex.R)\n\n# Load Necessary Libraries\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(foreign)    # For reading .sav files\nlibrary(ggplot2)    # For visualization\nlibrary(dplyr)      # For data manipulation\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'dplyr'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:stats':\n\n    filter, lag\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:base':\n\n    intersect, setdiff, setequal, union\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(gtsummary)  # For creating regression tables\nlibrary(officer)    # For exporting to Word\nlibrary(flextable)  # For table formatting\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'flextable'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:gtsummary':\n\n    continuous_summary\n```\n\n\n:::\n:::\n\n\n# Load and Inspect Data\n\n::: {.cell}\n\n```{.r .cell-code}\nadmissions <- read.spss(\"data/admissions.sav\", to.data.frame = TRUE)\nhead(admissions) # Display first few rows\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  row_number paiddeposit scholarship_yes_no Type_of_scholarship_offered Female\n1          7           1                  0                                  0\n2         12           0                  0                                  0\n3         19           1                  0                                  0\n4         23           1                  0                                  0\n5         25           0                  0                                  0\n6         28           0                  0                                  1\n             Race HS_rank HS_class_size HS_Quintile HS_CODE\n1 white               190           281        4/5   392835\n2 white               111           223        3/5   393655\n3 white               109           371        2/5    51830\n4 Asian                88           266        2/5   390527\n5 white                NA            NA              390870\n6 white                59           382        1/5   392655\n                  HS_NAME SAT_verbal ACT Honors_college_eligible\n1 FRANKLIN_REGIONAL_SR_HI        560  NA                     no \n2 CENTRAL_CATHOLIC_HIGH_S        600  NA                     no \n3 WESTCHESTER_HIGH_SCHOOL        550  NA                     no \n4 CEDAR_CLIFF_HIGH_SCHOOL        520  NA                     no \n5 HOLY_GHOST_PREPARATORY         650  NA                     no \n6 PENN_MANOR_HIGH_SCHOOL         460  20                     no \n  distancefromPitt state Number_of_family_alumni father_alumni grand_alumni\n1        14.228946    PA                       0             0            0\n2         7.162134    PA                       0             0            0\n3       232.363382    PA                       0             0            0\n4       163.462296    PA                       0             0            0\n5       261.534151    PA                       0             0            0\n6       192.493359    PA                       0             0            0\n  mother_alumni sibling_alumni step_parent_alumni other_family_alumni\n1             0              0                  0                   0\n2             0              0                  0                   0\n3             0              0                  0                   0\n4             0              0                  0                   0\n5             0              0                  0                   0\n6             0              0                  0                   0\n  SAT_composite ACT_as_SAT Max_Test_Score Training from_PA\n1          1180         NA           1180        0       1\n2          1150         NA           1150        0       1\n3          1190         NA           1190        0       1\n4          1140         NA           1140        0       1\n5          1200         NA           1200        0       1\n6           940        950            950        0       1\n               alumniYN SAT_math\n1 Family is not an alum      620\n2 Family is not an alum      550\n3 Family is not an alum      640\n4 Family is not an alum      620\n5 Family is not an alum      550\n6 Family is not an alum      480\n```\n\n\n:::\n:::\n\n\n# Data Preprocessing\n\n::: {.cell}\n\n```{.r .cell-code}\nadmissions_clean <- admissions %>% \n  dplyr::select(SAT_math, SAT_verbal, HS_class_size) %>% \n  na.omit()\n```\n:::\n\n\n# Simple Linear Regression: SAT Math ~ SAT Verbal\n\n::: {.cell}\n\n```{.r .cell-code}\nsimple_model <- lm(SAT_math ~ SAT_verbal, data = admissions_clean)\nsummary(simple_model) # Regression summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = SAT_math ~ SAT_verbal, data = admissions_clean)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-168.125  -43.568   -1.667   41.119  188.462 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 329.24934   19.49133   16.89   <2e-16 ***\nSAT_verbal    0.45572    0.03448   13.22   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 61.42 on 689 degrees of freedom\nMultiple R-squared:  0.2023,\tAdjusted R-squared:  0.2011 \nF-statistic: 174.7 on 1 and 689 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n### Interpretation:\n- **SAT Verbal has a positive effect on SAT Math scores** (Estimate = 0.45572, p < 0.001).\n- **Model explains ~20.2% of variance in SAT Math scores** (Adjusted R² = 0.2011), meaning SAT Verbal alone is a moderate predictor.\n- **Residuals appear reasonably distributed**, suggesting no major violations of normality assumptions.\n\n# Compute Fitted Values and Residuals\n\n::: {.cell}\n\n```{.r .cell-code}\nadmissions_clean$fitted_simple <- fitted(simple_model)\nadmissions_clean$residuals_simple <- residuals(simple_model)\n```\n:::\n\n\n# Compute Standardized Values\n\n::: {.cell}\n\n```{.r .cell-code}\nadmissions_clean$std_fitted_simple <- scale(admissions_clean$fitted_simple)\nadmissions_clean$std_residuals_simple <- scale(admissions_clean$residuals_simple)\n```\n:::\n\n\n# Visualization: Residuals vs. Fitted\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(admissions_clean, aes(x = std_fitted_simple, y = std_residuals_simple)) +\n  geom_point(color = \"blue\") +\n  geom_hline(yintercept = 0, linetype = \"dashed\", color = \"red\") +\n  labs(title = \"Standardized Residuals vs. Standardized Fitted Values (Simple Model)\",\n       x = \"Standardized Fitted Values\", y = \"Standardized Residuals\")\n```\n\n::: {.cell-output-display}\n![](admissions_R_ex_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n### Interpretation:\n- **Residuals are fairly symmetrically distributed** around zero, suggesting the linear model is appropriate.\n- **No major patterns** in residuals indicate homoscedasticity.\n\n# Histogram of Residuals\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(admissions_clean, aes(x = residuals_simple)) +\n  geom_histogram(bins = 30, fill = \"lightblue\", color = \"black\") +\n  labs(title = \"Histogram of Residuals (Simple Model)\", x = \"Residuals\", y = \"Frequency\")\n```\n\n::: {.cell-output-display}\n![](admissions_R_ex_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n### Interpretation:\n- **Residuals follow a normal-like distribution**, supporting the assumption of normality.\n\n# Correlation Analysis\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(admissions_clean[, c(\"SAT_math\", \"SAT_verbal\", \"fitted_simple\", \"residuals_simple\")], use = \"complete.obs\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  SAT_math    SAT_verbal fitted_simple residuals_simple\nSAT_math         1.0000000  4.497305e-01  4.497305e-01     8.931643e-01\nSAT_verbal       0.4497305  1.000000e+00  1.000000e+00    -5.014076e-16\nfitted_simple    0.4497305  1.000000e+00  1.000000e+00    -1.828283e-15\nresiduals_simple 0.8931643 -5.014076e-16 -1.828283e-15     1.000000e+00\n```\n\n\n:::\n:::\n\n\n### Interpretation:\n- **Strong positive correlation** between SAT Math and SAT Verbal (r ≈ 0.45).\n- **Fitted values highly correlate with SAT Verbal**, confirming its predictive power.\n\n# Multiple Linear Regression: SAT Math ~ SAT Verbal + HS Class Size\n\n::: {.cell}\n\n```{.r .cell-code}\nmultiple_model <- lm(SAT_math ~ SAT_verbal + HS_class_size, data = admissions_clean)\nsummary(multiple_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = SAT_math ~ SAT_verbal + HS_class_size, data = admissions_clean)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-165.924  -44.589   -1.418   40.825  197.261 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   314.14654   19.47735  16.129  < 2e-16 ***\nSAT_verbal      0.44864    0.03401  13.192  < 2e-16 ***\nHS_class_size   0.06030    0.01295   4.656 3.88e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 60.52 on 688 degrees of freedom\nMultiple R-squared:  0.2266,\tAdjusted R-squared:  0.2244 \nF-statistic: 100.8 on 2 and 688 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n### Interpretation:\n- **HS Class Size has a small but significant positive effect** (Estimate = 0.06030, p < 0.001).\n- **Explained variance increases to 22.4%**, showing a slight improvement over the simple model.\n\n# Visualization of SAT Verbal Effect\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(admissions_clean, aes(x = SAT_verbal, y = SAT_math)) +\n  geom_point(alpha = 0.5) +\n  geom_smooth(method = \"lm\", col = \"blue\") +\n  labs(title = \"Effect of SAT Verbal on SAT Math\", x = \"SAT Verbal\", y = \"SAT Math\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](admissions_R_ex_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n# Generate Regression Summary Table\n\n::: {.cell}\n\n```{.r .cell-code}\nmlr_table <- multiple_model %>% \n  tbl_regression(label = list(SAT_verbal = \"SAT Verbal Score\", HS_class_size = \"High School Class Size\")) %>%\n  modify_caption(\"Table 1: Multiple Linear Regression Results\") %>%\n  add_n()\n```\n:::\n\n\n# Save Table to Word\n\n::: {.cell}\n\n```{.r .cell-code}\nmlr_flextable <- as_flex_table(mlr_table)\ndoc <- read_docx()\ndoc <- body_add_flextable(doc, value = mlr_flextable)\nprint(doc, target = \"MLR_Results.docx\")\n```\n:::\n\n\n# Conclusion\n\n### Key Findings:\n1. **SAT Verbal scores significantly predict SAT Math scores**, explaining ~20% of the variance.\n2. **Adding HS Class Size improves the model slightly**, raising the explained variance to 22.4%.\n3. **Both models suggest a linear relationship**, with residuals showing normality and no major violations.\n\n### Implications:\n- Schools aiming to improve SAT Math scores may focus on strengthening verbal skills.\n- Class size appears to play a small but relevant role in performance.\n- Further research could explore additional predictors (e.g., socioeconomic factors, study habits).\n",
    "supporting": [
      "admissions_R_ex_files\\figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}