<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Barboza-Salerno">

<title>Statistics II Initial Assessment – Statistics for Social Work</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./MTF-solution.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-d9ea66fcd6c317012447f26e9c021348.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./MTF-solution.html">Solutions</a></li><li class="breadcrumb-item"><a href="./assessment_ans.html"><span class="chapter-title">Statistics II Initial Assessment</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistics for Social Work</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Statistics for Social Work</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Course Overview</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./syllabus.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Syllabus: Statistics for Social Work</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Assignments.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Assignments and Due Dates</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-introduction.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Introduction to the Course</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Regression Mechanics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-simple-regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Introduction to Simple Linear Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-multiple-regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Multiple Linear Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-effect-sizes.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Effect Sizes</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-assumptions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Regression Assumptions</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Advanced Regression Techniques</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-logistic-regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Logistic Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-mediation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Mediation, Moderation, and Conditional Process Models (Part 1)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-moderation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Mediation, Moderation, and Conditional Process Models (Part 2)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07a-moderation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Mediation, Moderation, and Conditional Process Models (Part 3)</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Measurement &amp; Factor Analysis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-efa.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">EFA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./efa_R.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">EFA in R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-lca.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">LCA</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Applications</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-final-project.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Final Project</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./assignment.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Assignment 1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./slides/inclass.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">In Class Assignment</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./slides/medmod/mediationR.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Simple Mediation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./logistic.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Logistic Regression Example</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./slides/moderation/moderation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Moderation Analysis</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Case Studies &amp; Data Applications</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Monitoring-the-future-example.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lab 1: Monitoring the Future</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./infant_mortality.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Infant Mortality Example</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./PRAMS_Correlation_Analysis.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Partial and Semi-Partial Correlation Analysis with PRAMS 8 Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cohensd.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Analysis of Area Deprivation Disparities Using Cohen’s D</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./admissions_R_ex.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Admissions Data Analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./nscaw.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">NSCAW I In-Class Exercise</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">Additional Resources</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./reading.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Required Course Materials</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./dataweb.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Data Sources</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">References</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./resources.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Resources for learning and applying R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./learning-r.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Learning R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r-style.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">R Style Suggestions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./dataweb.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Data Sources</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./open-source-software.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Open Source Software</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true">
 <span class="menu-text">Assignments</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ass1writeup.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Assignment 1 Write-up</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./assign2.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Assignment 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./final.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Final Stats II Assignment</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="true">
 <span class="menu-text">Solutions</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./MTF-solution.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lab 1 - SOLUTION</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./assessment_ans.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Statistics II Initial Assessment</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#question-1-introduction-to-data" id="toc-question-1-introduction-to-data" class="nav-link active" data-scroll-target="#question-1-introduction-to-data">Question 1: Introduction to Data</a></li>
  <li><a href="#question-2-independence" id="toc-question-2-independence" class="nav-link" data-scroll-target="#question-2-independence">Question 2: Independence</a></li>
  <li><a href="#question-3a-b-interquartile-range" id="toc-question-3a-b-interquartile-range" class="nav-link" data-scroll-target="#question-3a-b-interquartile-range">Question 3a-b: Interquartile Range</a></li>
  <li><a href="#question-3c-iqr-vs-standard-deviation" id="toc-question-3c-iqr-vs-standard-deviation" class="nav-link" data-scroll-target="#question-3c-iqr-vs-standard-deviation">Question 3c: IQR vs Standard Deviation</a></li>
  <li><a href="#question-4-contingency-tables" id="toc-question-4-contingency-tables" class="nav-link" data-scroll-target="#question-4-contingency-tables">Question 4: Contingency Tables</a></li>
  <li><a href="#question-5-probability-distributions" id="toc-question-5-probability-distributions" class="nav-link" data-scroll-target="#question-5-probability-distributions">Question 5: Probability Distributions</a></li>
  <li><a href="#question-6a-b-independent-random-variables" id="toc-question-6a-b-independent-random-variables" class="nav-link" data-scroll-target="#question-6a-b-independent-random-variables">Question 6a-b: Independent Random Variables</a></li>
  <li><a href="#question-6c-independence-explained" id="toc-question-6c-independence-explained" class="nav-link" data-scroll-target="#question-6c-independence-explained">Question 6c: Independence Explained</a></li>
  <li><a href="#question-7-five-independent-people" id="toc-question-7-five-independent-people" class="nav-link" data-scroll-target="#question-7-five-independent-people">Question 7: Five Independent People</a></li>
  <li><a href="#question-8-covid-19-conditional-probability" id="toc-question-8-covid-19-conditional-probability" class="nav-link" data-scroll-target="#question-8-covid-19-conditional-probability">Question 8: COVID-19 Conditional Probability</a></li>
  <li><a href="#question-9a-tree-diagram" id="toc-question-9a-tree-diagram" class="nav-link" data-scroll-target="#question-9a-tree-diagram">Question 9a: Tree Diagram</a></li>
  <li><a href="#question-9b-c-tree-diagram-probabilities" id="toc-question-9b-c-tree-diagram-probabilities" class="nav-link" data-scroll-target="#question-9b-c-tree-diagram-probabilities">Question 9b-c: Tree Diagram Probabilities</a></li>
  <li><a href="#question-10-mean-variance-sd" id="toc-question-10-mean-variance-sd" class="nav-link" data-scroll-target="#question-10-mean-variance-sd">Question 10: Mean, Variance, SD</a></li>
  <li><a href="#question-11-z-scores" id="toc-question-11-z-scores" class="nav-link" data-scroll-target="#question-11-z-scores">Question 11: Z-scores</a></li>
  <li><a href="#question-12a-c-licensing-exam-z-scores" id="toc-question-12a-c-licensing-exam-z-scores" class="nav-link" data-scroll-target="#question-12a-c-licensing-exam-z-scores">Question 12a-c: Licensing Exam Z-scores</a></li>
  <li><a href="#question-12d-e-percentiles" id="toc-question-12d-e-percentiles" class="nav-link" data-scroll-target="#question-12d-e-percentiles">Question 12d-e: Percentiles</a></li>
  <li><a href="#question-13a-b-sat-scores" id="toc-question-13a-b-sat-scores" class="nav-link" data-scroll-target="#question-13a-b-sat-scores">Question 13a-b: SAT Scores</a></li>
  <li><a href="#question-13c-social-justice" id="toc-question-13c-social-justice" class="nav-link" data-scroll-target="#question-13c-social-justice">Question 13c: Social Justice</a></li>
  <li><a href="#question-14-binomial-distribution" id="toc-question-14-binomial-distribution" class="nav-link" data-scroll-target="#question-14-binomial-distribution">Question 14: Binomial Distribution</a></li>
  <li><a href="#question-15a-hypothesis-testing-framework" id="toc-question-15a-hypothesis-testing-framework" class="nav-link" data-scroll-target="#question-15a-hypothesis-testing-framework">Question 15a: Hypothesis Testing Framework</a></li>
  <li><a href="#question-15b-innocent-vs-not-guilty" id="toc-question-15b-innocent-vs-not-guilty" class="nav-link" data-scroll-target="#question-15b-innocent-vs-not-guilty">Question 15b: Innocent vs Not Guilty</a></li>
  <li><a href="#question-16a-confidence-interval" id="toc-question-16a-confidence-interval" class="nav-link" data-scroll-target="#question-16a-confidence-interval">Question 16a: Confidence Interval</a></li>
  <li><a href="#question-16b-ci-interpretation" id="toc-question-16b-ci-interpretation" class="nav-link" data-scroll-target="#question-16b-ci-interpretation">Question 16b: CI Interpretation</a></li>
  <li><a href="#question-17-hypothesis-setup" id="toc-question-17-hypothesis-setup" class="nav-link" data-scroll-target="#question-17-hypothesis-setup">Question 17: Hypothesis Setup</a></li>
  <li><a href="#question-18-p-value-vs-significance-level" id="toc-question-18-p-value-vs-significance-level" class="nav-link" data-scroll-target="#question-18-p-value-vs-significance-level">Question 18: P-value vs Significance Level</a></li>
  <li><a href="#question-19-p-value-frequency" id="toc-question-19-p-value-frequency" class="nav-link" data-scroll-target="#question-19-p-value-frequency">Question 19: P-value Frequency</a></li>
  <li><a href="#question-20-practical-vs-statistical-significance" id="toc-question-20-practical-vs-statistical-significance" class="nav-link" data-scroll-target="#question-20-practical-vs-statistical-significance">Question 20: Practical vs Statistical Significance</a></li>
  <li><a href="#question-21-dependent-sample-t-test" id="toc-question-21-dependent-sample-t-test" class="nav-link" data-scroll-target="#question-21-dependent-sample-t-test">Question 21: Dependent Sample t-test</a></li>
  <li><a href="#question-22a-b-independent-samples-t-test" id="toc-question-22a-b-independent-samples-t-test" class="nav-link" data-scroll-target="#question-22a-b-independent-samples-t-test">Question 22a-b: Independent Samples t-test</a></li>
  <li><a href="#question-22-answer" id="toc-question-22-answer" class="nav-link" data-scroll-target="#question-22-answer">Question 22: Answer</a></li>
  <li><a href="#question-23a-anova-hypotheses" id="toc-question-23a-anova-hypotheses" class="nav-link" data-scroll-target="#question-23a-anova-hypotheses">Question 23a: ANOVA Hypotheses</a></li>
  <li><a href="#question-23b-anova-results" id="toc-question-23b-anova-results" class="nav-link" data-scroll-target="#question-23b-anova-results">Question 23b: ANOVA Results</a></li>
  <li><a href="#part-ii-applied-analysis-overview" id="toc-part-ii-applied-analysis-overview" class="nav-link" data-scroll-target="#part-ii-applied-analysis-overview">Part II: Applied Analysis Overview</a></li>
  <li><a href="#part-ii-analysis-approach" id="toc-part-ii-analysis-approach" class="nav-link" data-scroll-target="#part-ii-analysis-approach">Part II: Analysis Approach</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./MTF-solution.html">Solutions</a></li><li class="breadcrumb-item"><a href="./assessment_ans.html"><span class="chapter-title">Statistics II Initial Assessment</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Statistics II Initial Assessment</span></h1>
<p class="subtitle lead">January 13, 2026</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Barboza-Salerno </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="question-1-introduction-to-data" class="level2">
<h2 class="anchored" data-anchor-id="question-1-introduction-to-data">Question 1: Introduction to Data</h2>
<p><strong>Question:</strong> The table below describes an intervention to reduce PTSD among violence-exposed youth.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>0-365 days PTSD</th>
<th>0-365 days No PTSD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Treatment</td>
<td>45</td>
<td>179</td>
</tr>
<tr class="even">
<td>Control</td>
<td>28</td>
<td>199</td>
</tr>
</tbody>
</table>
<ol type="a">
<li>Among all youth in a treatment group, what proportion had PTSD by the end of the first year?</li>
<li>What proportion of youth had PTSD in the control group by the end of the first year?</li>
</ol>
<p><strong>Answer:</strong></p>
<ul>
<li><strong>1a.</strong> Treatment: <span class="math inline">\(\frac{45}{224} = 0.201\)</span> or <span class="math inline">\(20.1\%\)</span></li>
<li><strong>1b.</strong> Control: <span class="math inline">\(\frac{28}{227} = 0.123\)</span> or <span class="math inline">\(12.3\%\)</span></li>
</ul>
<hr>
</section>
<section id="question-2-independence" class="level2">
<h2 class="anchored" data-anchor-id="question-2-independence">Question 2: Independence</h2>
<p><strong>Question:</strong> True or False: A pair of variables are either related or not (independent). Two variables can’t be both associated and independent.</p>
<p><strong>Answer: True</strong></p>
<p>Two variables cannot be both associated and independent. Independence means that knowing the value of one variable provides no information about the other variable. If variables are associated (related), they are by definition not independent.</p>
<hr>
</section>
<section id="question-3a-b-interquartile-range" class="level2">
<h2 class="anchored" data-anchor-id="question-3a-b-interquartile-range">Question 3a-b: Interquartile Range</h2>
<p><strong>Question:</strong></p>
<ol type="a">
<li>Assume that <span class="math inline">\(Q_1\)</span> describes the 25th percentile. Define <span class="math inline">\(Q_1\)</span> in words.</li>
<li>Assume <span class="math inline">\(Q_3\)</span> is the 75th percentile. <span class="math inline">\(Q_3 = 300\)</span>; <span class="math inline">\(Q_1 = 100\)</span>. Calculate the IQR.</li>
</ol>
<p><strong>Answer:</strong></p>
<p><strong>3a.</strong> <span class="math inline">\(Q_1\)</span> is the value below which <span class="math inline">\(25\%\)</span> of the data falls. It represents the first quartile, meaning one-quarter of observations are smaller than this value.</p>
<p><strong>3b.</strong> <span class="math inline">\(\text{IQR} = Q_3 - Q_1 = 300 - 100 = 200\)</span></p>
<hr>
</section>
<section id="question-3c-iqr-vs-standard-deviation" class="level2">
<h2 class="anchored" data-anchor-id="question-3c-iqr-vs-standard-deviation">Question 3c: IQR vs Standard Deviation</h2>
<p><strong>Question:</strong> Describe why extreme observations affect the standard deviation more than the interquartile range (IQR).</p>
<p><strong>Answer:</strong></p>
<p>The IQR uses only the middle <span class="math inline">\(50\%\)</span> of data, ignoring the top and bottom <span class="math inline">\(25\%\)</span>. Standard deviation uses squared deviations from the mean, so extreme values (which have large deviations) are squared and heavily weighted. The IQR is resistant to outliers; SD is not.</p>
<hr>
</section>
<section id="question-4-contingency-tables" class="level2">
<h2 class="anchored" data-anchor-id="question-4-contingency-tables">Question 4: Contingency Tables</h2>
<p><strong>Question:</strong> Use the table below to answer the following questions:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>None</th>
<th>Small</th>
<th>Big</th>
<th>Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Yes</td>
<td>.406</td>
<td>.458</td>
<td>.136</td>
<td>1</td>
</tr>
<tr class="even">
<td>No</td>
<td>.113</td>
<td>.748</td>
<td>.139</td>
<td>1</td>
</tr>
</tbody>
</table>
<ol type="a">
<li>What does the .458 represent in the table?</li>
<li>What does the .139 at the intersection of No and Big represent?</li>
</ol>
<p><strong>Answer:</strong></p>
<p><strong>4a.</strong> The .458 represents <span class="math inline">\(P(\text{Small}|\text{Yes}) = 45.8\%\)</span> - the conditional probability of “Small” given “Yes”</p>
<p><strong>4b.</strong> The .139 represents <span class="math inline">\(P(\text{Big}|\text{No}) = 13.9\%\)</span> - the conditional probability of “Big” given “No”</p>
<hr>
</section>
<section id="question-5-probability-distributions" class="level2">
<h2 class="anchored" data-anchor-id="question-5-probability-distributions">Question 5: Probability Distributions</h2>
<p><strong>Question:</strong> The table below suggests three salary distributions for social workers in Columbus. Only one is correct. Which one must it be? What is wrong with the other two?</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Income ($1000s)</th>
<th>0-25</th>
<th>25-50</th>
<th>50-100</th>
<th>100+</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A</td>
<td>.18</td>
<td>.39</td>
<td>.33</td>
<td>.16</td>
</tr>
<tr class="even">
<td>B</td>
<td>.38</td>
<td>-.27</td>
<td>.52</td>
<td>.37</td>
</tr>
<tr class="odd">
<td>C</td>
<td>.28</td>
<td>.27</td>
<td>.29</td>
<td>.16</td>
</tr>
</tbody>
</table>
<p><strong>Answer:</strong></p>
<p><strong>Correct: A</strong> (probabilities sum to <span class="math inline">\(1.06 \approx 1.00\)</span>)</p>
<p><strong>B is wrong:</strong> Contains negative probability <span class="math inline">\((-.27)\)</span>, which is impossible</p>
<p><strong>C is wrong:</strong> Sums to exactly <span class="math inline">\(1.00\)</span> but appears less plausible than A given context</p>
<hr>
</section>
<section id="question-6a-b-independent-random-variables" class="level2">
<h2 class="anchored" data-anchor-id="question-6a-b-independent-random-variables">Question 6a-b: Independent Random Variables</h2>
<p><strong>Question:</strong> About 9% of people exposed to a natural disaster develop PTSD. Suppose 2 people are selected at random. Assume independence.</p>
<ol type="a">
<li>What is the probability they both developed symptoms?</li>
<li>What is the probability that neither did?</li>
</ol>
<p><strong>Answer:</strong></p>
<p><strong>6a.</strong> <span class="math inline">\(P(\text{both}) = 0.09 \times 0.09 = 0.0081\)</span> or <span class="math inline">\(0.81\%\)</span></p>
<p><strong>6b.</strong> <span class="math inline">\(P(\text{neither}) = 0.91 \times 0.91 = 0.8281\)</span> or <span class="math inline">\(82.81\%\)</span></p>
<p>Note: this is also <span class="math inline">\((1-0.09) \times (1-0.09) = 0.8281\)</span></p>
<hr>
</section>
<section id="question-6c-independence-explained" class="level2">
<h2 class="anchored" data-anchor-id="question-6c-independence-explained">Question 6c: Independence Explained</h2>
<p><strong>Question:</strong> Explain what ‘independence’ means and why your calculation depends on this assumption.</p>
<p><strong>Answer:</strong></p>
<p>Independence means one person developing PTSD doesn’t affect the probability of another person developing PTSD. The events are unrelated.</p>
<p>We can multiply individual probabilities only under independence: <span class="math inline">\(P(A \cap B) = P(A) \times P(B)\)</span>.</p>
<p>Without independence, we’d need conditional probabilities: <span class="math inline">\(P(A \cap B) = P(A) \times P(B|A)\)</span>.</p>
<hr>
</section>
<section id="question-7-five-independent-people" class="level2">
<h2 class="anchored" data-anchor-id="question-7-five-independent-people">Question 7: Five Independent People</h2>
<p><strong>Question:</strong> Use the data from above. Now, suppose 5 people are selected at random.</p>
<ol type="a">
<li>What is the probability they all develop PTSD symptoms?</li>
<li>What is the probability none did?</li>
</ol>
<p><strong>Answer:</strong></p>
<p><strong>7a.</strong> <span class="math inline">\(P(\text{all 5}) = (0.09)^5 = 0.0000059 \approx 0.00059\%\)</span></p>
<p><strong>7b.</strong> <span class="math inline">\(P(\text{none}) = (0.91)^5 = 0.6240\)</span> or <span class="math inline">\(62.40\%\)</span></p>
<hr>
</section>
<section id="question-8-covid-19-conditional-probability" class="level2">
<h2 class="anchored" data-anchor-id="question-8-covid-19-conditional-probability">Question 8: COVID-19 Conditional Probability</h2>
<p><strong>Question:</strong> Find the probability a randomly selected person who was not given the COVID-19 vaccine died from COVID using the following table:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Vaccinated Yes</th>
<th>Vaccinated No</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Lived</td>
<td>.0382</td>
<td>.8252</td>
</tr>
<tr class="even">
<td>Died</td>
<td>.0010</td>
<td>.1356</td>
</tr>
</tbody>
</table>
<p><strong>Answer:</strong></p>
<p><span class="math display">\[P(\text{Died}|\text{Not Vaccinated}) = \frac{P(\text{Not Vax} \cap \text{Died})}{P(\text{Not Vax})}\]</span></p>
<p><span class="math display">\[= \frac{0.1356}{0.8252 + 0.1356} = \frac{0.1356}{0.9608} = 0.1411 \text{ or } 14.11\%\]</span></p>
<hr>
</section>
<section id="question-9a-tree-diagram" class="level2">
<h2 class="anchored" data-anchor-id="question-9a-tree-diagram">Question 9a: Tree Diagram</h2>
<p><strong>Question:</strong> Create a tree diagram for the COVID-19 vaccination data.</p>
<p><strong>Answer:</strong></p>
<pre><code>Start 
├─ Vaccinated (0.0392)
│  ├─ Lived (0.0382)
│  └─ Died (0.0010)
│
└─ Not Vaccinated (0.9608)
   ├─ Lived (0.8252)
   └─ Died (0.1356)</code></pre>
<hr>
</section>
<section id="question-9b-c-tree-diagram-probabilities" class="level2">
<h2 class="anchored" data-anchor-id="question-9b-c-tree-diagram-probabilities">Question 9b-c: Tree Diagram Probabilities</h2>
<p><strong>Question:</strong> Use the tree diagram to calculate:</p>
<ol start="2" type="a">
<li>The probability that a random person was vaccinated and lived</li>
<li>The probability that the person died (regardless of vaccination status)</li>
</ol>
<p><strong>Answer:</strong></p>
<p><strong>9b.</strong> <span class="math inline">\(P(\text{Vaccinated} \cap \text{Lived}) = 0.0382\)</span></p>
<p><strong>9c.</strong> <span class="math inline">\(P(\text{Died}) = P(\text{Vax} \cap \text{Died}) + P(\text{Not Vax} \cap \text{Died})\)</span></p>
<p><span class="math display">\[= 0.0010 + 0.1356 = 0.1366 \text{ or } 13.66\%\]</span></p>
<hr>
</section>
<section id="question-10-mean-variance-sd" class="level2">
<h2 class="anchored" data-anchor-id="question-10-mean-variance-sd">Question 10: Mean, Variance, SD</h2>
<p><strong>Question:</strong> Compute the variable’s mean, variance, and standard deviation.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th><span class="math inline">\(x_i\)</span></th>
<th><span class="math inline">\(P(X = x_i)\)</span></th>
<th><span class="math inline">\(x_i \cdot P(X = x_i)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>0.20</td>
<td>0.00</td>
</tr>
<tr class="even">
<td>137</td>
<td>0.55</td>
<td>75.35</td>
</tr>
<tr class="odd">
<td>170</td>
<td>0.25</td>
<td>42.50</td>
</tr>
</tbody>
</table>
<p><strong>Answer:</strong></p>
<p><strong>Mean:</strong> <span class="math inline">\(\mu = \sum[x_i \cdot P(x_i)] = 0.00 + 75.35 + 42.50 = 117.85\)</span></p>
<p><strong>Variance:</strong> <span class="math inline">\(\sigma^2 = \sum[(x_i - \mu)^2 \cdot P(x_i)]\)</span></p>
<ul>
<li><span class="math inline">\((0 - 117.85)^2 \times 0.20 = 2{,}777.70\)</span></li>
<li><span class="math inline">\((137 - 117.85)^2 \times 0.55 = 201.70\)</span></li>
<li><span class="math inline">\((170 - 117.85)^2 \times 0.25 = 679.56\)</span></li>
<li><span class="math inline">\(\sigma^2 = 3{,}659\)</span></li>
</ul>
<p><strong>Standard Deviation:</strong> <span class="math inline">\(\sigma = \sqrt{3{,}659} = 60\)</span></p>
<hr>
</section>
<section id="question-11-z-scores" class="level2">
<h2 class="anchored" data-anchor-id="question-11-z-scores">Question 11: Z-scores</h2>
<p><strong>Question:</strong> Let <span class="math inline">\(X\)</span> represent a random variable from <span class="math inline">\(N(\mu = 3, \sigma = 2)\)</span>. Suppose we observe that <span class="math inline">\(x = 5.19\)</span>.</p>
<ol type="a">
<li>Find the Z-score of <span class="math inline">\(x\)</span></li>
<li>Use the Z-score to determine how many standard deviations above or below the mean, <span class="math inline">\(x\)</span>, falls.</li>
</ol>
<p><strong>Answer:</strong></p>
<p><strong>11a.</strong> <span class="math inline">\(Z = \frac{x - \mu}{\sigma} = \frac{5.19 - 3}{2} = 1.095\)</span></p>
<p><strong>11b.</strong> The observation <span class="math inline">\(x = 5.19\)</span> falls <strong>1.095 standard deviations above the mean</strong>.</p>
<hr>
</section>
<section id="question-12a-c-licensing-exam-z-scores" class="level2">
<h2 class="anchored" data-anchor-id="question-12a-c-licensing-exam-z-scores">Question 12a-c: Licensing Exam Z-scores</h2>
<p><strong>Question:</strong> The social work licensing exam follows a nearly normal distribution with mean 92.6 and standard deviation 3.6.</p>
<ol type="a">
<li>Compute the Z-score for an exam score of 95.4</li>
<li>Compute the Z-score for an exam of 85.8</li>
<li>Which of the two observations is more unusual?</li>
</ol>
<p><strong>Answer:</strong></p>
<p><strong>12a.</strong> <span class="math inline">\(Z = \frac{95.4 - 92.6}{3.6} = 0.778\)</span></p>
<p><strong>12b.</strong> <span class="math inline">\(Z = \frac{85.8 - 92.6}{3.6} = -1.889\)</span></p>
<p><strong>12c.</strong> The score of <strong>85.8 is more unusual</strong> <span class="math inline">\((|Z| = 1.889 \text{ vs. } 0.778)\)</span></p>
<hr>
</section>
<section id="question-12d-e-percentiles" class="level2">
<h2 class="anchored" data-anchor-id="question-12d-e-percentiles">Question 12d-e: Percentiles</h2>
<p><strong>Question:</strong></p>
<ol start="4" type="a">
<li>Both students come to you to calculate and interpret their percentile on the exam.</li>
<li>What proportion of test takers scored higher than these two?</li>
</ol>
<p><strong>Answer:</strong></p>
<p><strong>12d. Percentiles:</strong></p>
<ul>
<li>Score 95.4 <span class="math inline">\((Z = 0.778)\)</span>: approximately <strong>78th percentile</strong></li>
<li>Score 85.8 <span class="math inline">\((Z = -1.889)\)</span>: approximately <strong>3rd percentile</strong></li>
</ul>
<p><strong>12e. Proportion scoring higher:</strong></p>
<ul>
<li>Higher than 95.4: approximately <span class="math inline">\(22\%\)</span></li>
<li>Higher than 85.8: approximately <span class="math inline">\(97\%\)</span></li>
</ul>
<hr>
</section>
<section id="question-13a-b-sat-scores" class="level2">
<h2 class="anchored" data-anchor-id="question-13a-b-sat-scores">Question 13a-b: SAT Scores</h2>
<p><strong>Question:</strong> The SAT test is approximately normally distributed with <span class="math inline">\(\mu = 1500\)</span>, <span class="math inline">\(\sigma = 300\)</span>.</p>
<ol type="a">
<li>What is the probability of scoring at least 1630 on the SAT?</li>
<li>One year something unusual happened and more than 75% of test takers scored above 1600. How does that affect the calculation?</li>
</ol>
<p><strong>Answer:</strong></p>
<p><strong>13a.</strong> <span class="math inline">\(Z = \frac{1630 - 1500}{300} = 0.433\)</span></p>
<p><span class="math inline">\(P(X \geq 1630) \approx 0.3325\)</span> or <span class="math inline">\(33.25\%\)</span></p>
<p><strong>13b.</strong> This violates normality assumptions. If <span class="math inline">\(75\%\)</span> scored above 1600, the distribution is no longer <span class="math inline">\(N(1500, 300)\)</span>. We cannot use normal distribution calculations; we’d need the actual distribution.</p>
<hr>
</section>
<section id="question-13c-social-justice" class="level2">
<h2 class="anchored" data-anchor-id="question-13c-social-justice">Question 13c: Social Justice</h2>
<p><strong>Question:</strong> From a social justice standpoint, describe the problem with interpreting aptitude using a statistical analysis.</p>
<p><strong>Answer:</strong></p>
<p>Aptitude tests may reflect socioeconomic advantages (test prep access, quality education, tutoring, educational resources) rather than innate ability. They can perpetuate inequality by disadvantaging students from under-resourced backgrounds, marginalized communities, and those who lack access to test preparation resources. Statistical analysis treats scores as objective measures but ignores systemic inequities.</p>
<hr>
</section>
<section id="question-14-binomial-distribution" class="level2">
<h2 class="anchored" data-anchor-id="question-14-binomial-distribution">Question 14: Binomial Distribution</h2>
<p><strong>Question:</strong> On 70% of days, a therapist’s office admits at least one new client. On 30% of the days, no clients are admitted. What is the probability that the therapist will admit a new client on exactly three days this week?</p>
<p><strong>Answer:</strong></p>
<p>Using binomial theorem: <span class="math inline">\(P(X = 3) = \binom{7}{3} \times (0.70)^3 \times (0.30)^4\)</span></p>
<ul>
<li><span class="math inline">\(\binom{7}{3} = 35\)</span></li>
<li><span class="math inline">\((0.70)^3 = 0.343\)</span></li>
<li><span class="math inline">\((0.30)^4 = 0.0081\)</span></li>
<li><span class="math inline">\(P(X = 3) = 35 \times 0.343 \times 0.0081 = 0.0972\)</span> or <span class="math inline">\(9.72\%\)</span></li>
</ul>
<hr>
</section>
<section id="question-15a-hypothesis-testing-framework" class="level2">
<h2 class="anchored" data-anchor-id="question-15a-hypothesis-testing-framework">Question 15a: Hypothesis Testing Framework</h2>
<p><strong>Question:</strong> A US court is weighing two possible claims about a defendant: she is not guilty or guilty. How can a hypothesis testing framework be used to evaluate these claims?</p>
<p><strong>Answer:</strong></p>
<ul>
<li><span class="math inline">\(H_0\)</span> <strong>(null hypothesis):</strong> Defendant is not guilty</li>
<li><span class="math inline">\(H_1\)</span> <strong>(alternative hypothesis):</strong> Defendant is guilty</li>
<li>Burden of proof is on prosecution to reject <span class="math inline">\(H_0\)</span></li>
<li>Requires evidence “beyond reasonable doubt” (like <span class="math inline">\(\alpha\)</span> level)</li>
<li><strong>Type I error:</strong> Convicting an innocent person</li>
<li><strong>Type II error:</strong> Acquitting a guilty person</li>
</ul>
<hr>
</section>
<section id="question-15b-innocent-vs-not-guilty" class="level2">
<h2 class="anchored" data-anchor-id="question-15b-innocent-vs-not-guilty">Question 15b: Innocent vs Not Guilty</h2>
<p><strong>Question:</strong> What is the problem with falsely using the term ‘innocent’ rather than ‘not guilty’ in this framework?</p>
<p><strong>Answer:</strong></p>
<p>“Not guilty” means insufficient evidence to prove guilt beyond reasonable doubt. “Innocent” implies proof of non-involvement.</p>
<p>Courts don’t prove innocence; they determine if guilt is proven. This mirrors statistics: we reject or fail to reject <span class="math inline">\(H_0\)</span>, but never “accept” or “prove” <span class="math inline">\(H_0\)</span>. Failing to reject <span class="math inline">\(H_0 \neq\)</span> proving <span class="math inline">\(H_0\)</span> is true.</p>
<hr>
</section>
<section id="question-16a-confidence-interval" class="level2">
<h2 class="anchored" data-anchor-id="question-16a-confidence-interval">Question 16a: Confidence Interval</h2>
<p><strong>Question:</strong> In a sample of 100 students from the 2022 NCHS, the average number of days per year a child was reported ill was 2.78, with a standard deviation of 2.56 days. Compute a 95% confidence interval. Assume conditions for normality are met.</p>
<p><strong>Answer:</strong></p>
<p><span class="math display">\[SE = \frac{s}{\sqrt{n}} = \frac{2.56}{\sqrt{100}} = 0.256\]</span></p>
<p><span class="math display">\[95\% \text{ CI} = \bar{x} \pm (1.96 \times SE) = 2.78 \pm (1.96 \times 0.256)\]</span></p>
<p><span class="math display">\[= 2.78 \pm 0.502\]</span></p>
<p><strong>95% CI: (2.28, 3.28) days</strong></p>
<hr>
</section>
<section id="question-16b-ci-interpretation" class="level2">
<h2 class="anchored" data-anchor-id="question-16b-ci-interpretation">Question 16b: CI Interpretation</h2>
<p><strong>Question:</strong> Interpret the confidence interval.</p>
<p><strong>Answer:</strong></p>
<p>We are 95% confident that the true average number of days per year all children in the NCHS population are reported ill falls between 2.28 and 3.28 days.</p>
<p>This means if we repeated this sampling process many times, approximately 95% of the resulting confidence intervals would contain the true population mean.</p>
<hr>
</section>
<section id="question-17-hypothesis-setup" class="level2">
<h2 class="anchored" data-anchor-id="question-17-hypothesis-setup">Question 17: Hypothesis Setup</h2>
<p><strong>Question:</strong> UCLA estimates the cost of in-state tuition is $23,000/year. I estimate it at $33,000/year. What are the null and alternative hypotheses to test whether this claim is accurate?</p>
<p><strong>Answer:</strong></p>
<p><span class="math inline">\(H_0: \mu = \$23{,}000\)</span> (UCLA’s estimate is correct)</p>
<p><span class="math inline">\(H_1: \mu \neq \$23{,}000\)</span> (UCLA’s estimate is not correct)</p>
<p>This is a two-tailed test since we’re testing whether the claim is accurate (could be higher or lower), not specifically testing a directional hypothesis.</p>
<hr>
</section>
<section id="question-18-p-value-vs-significance-level" class="level2">
<h2 class="anchored" data-anchor-id="question-18-p-value-vs-significance-level">Question 18: P-value vs Significance Level</h2>
<p><strong>Question:</strong> What is the substantive difference between a p-value and the significance level of a test?</p>
<p><strong>Answer:</strong></p>
<p><strong>P-value:</strong> The probability of observing data as extreme as (or more extreme than) what we observed, assuming <span class="math inline">\(H_0\)</span> is true. Calculated from the data after the study.</p>
<p><strong>Significance level</strong> <span class="math inline">\((\alpha)\)</span><strong>:</strong> The threshold we set <strong>before</strong> conducting the test to determine whether to reject <span class="math inline">\(H_0\)</span>. Chosen by the researcher (commonly 0.05).</p>
<p><strong>Key difference:</strong> <span class="math inline">\(\alpha\)</span> is predetermined; p-value is calculated. We reject <span class="math inline">\(H_0\)</span> if p-value <span class="math inline">\(&lt; \alpha\)</span>.</p>
<hr>
</section>
<section id="question-19-p-value-frequency" class="level2">
<h2 class="anchored" data-anchor-id="question-19-p-value-frequency">Question 19: P-value Frequency</h2>
<p><strong>Question:</strong> If the null hypothesis is true, how often should the p-value be less than .10?</p>
<p><strong>Answer:</strong></p>
<p><strong>10% of the time</strong></p>
<p>If the null hypothesis is true, the p-value follows a uniform distribution between 0 and 1. Therefore, <span class="math inline">\(P(\text{p-value} &lt; 0.10) = 0.10\)</span>.</p>
<p>This is exactly the definition of the significance level—it represents the probability of a Type I error (rejecting a true null hypothesis).</p>
<hr>
</section>
<section id="question-20-practical-vs-statistical-significance" class="level2">
<h2 class="anchored" data-anchor-id="question-20-practical-vs-statistical-significance">Question 20: Practical vs Statistical Significance</h2>
<p><strong>Question:</strong> Describe the difference between practical and statistical significance. Provide an example.</p>
<p><strong>Answer:</strong></p>
<p><strong>Statistical significance:</strong> Result is unlikely due to chance alone (p-value <span class="math inline">\(&lt; \alpha\)</span>). Depends on sample size.</p>
<p><strong>Practical significance:</strong> Result is meaningful in real-world terms. Depends on effect size.</p>
<p><strong>Example:</strong> With <span class="math inline">\(n=1{,}000{,}000\)</span>, a reading intervention increases test scores by 0.5 points <span class="math inline">\((p &lt; 0.001)\)</span>. Statistically significant but practically meaningless—0.5 points won’t change educational outcomes. A 10-point increase might be practically significant even if <span class="math inline">\(p = 0.06\)</span>.</p>
<hr>
</section>
<section id="question-21-dependent-sample-t-test" class="level2">
<h2 class="anchored" data-anchor-id="question-21-dependent-sample-t-test">Question 21: Dependent Sample t-test</h2>
<p><strong>Question:</strong> Set up and implement a hypothesis test to determine whether, on average, there is a difference in outcomes for the treatment and control group using a dependent sample t-test. Summary statistics: <span class="math inline">\(N=73\)</span>; mean difference <span class="math inline">\(= 12.76\)</span>, SD of difference <span class="math inline">\(= 14.26\)</span>.</p>
<p><strong>Answer:</strong></p>
<p><strong>Hypotheses:</strong> <span class="math inline">\(H_0: \mu_{\text{diff}} = 0\)</span> vs.&nbsp;<span class="math inline">\(H_1: \mu_{\text{diff}} \neq 0\)</span></p>
<p><span class="math display">\[SE = \frac{14.26}{\sqrt{73}} = 1.669\]</span></p>
<p><span class="math display">\[t = \frac{12.76}{1.669} = 7.65, \quad df = 72\]</span></p>
<p><strong>Conclusion:</strong> With <span class="math inline">\(t = 7.65\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>. We reject <span class="math inline">\(H_0\)</span>. Strong evidence of a significant difference between treatment and control groups.</p>
<hr>
</section>
<section id="question-22a-b-independent-samples-t-test" class="level2">
<h2 class="anchored" data-anchor-id="question-22a-b-independent-samples-t-test">Question 22a-b: Independent Samples t-test</h2>
<p><strong>Question:</strong> The summary statistics below show newborn weights for mothers who smoked and did not smoke during pregnancy.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Smoked</th>
<th>Did not smoke</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mean</td>
<td>6.78</td>
<td>7.18</td>
</tr>
<tr class="even">
<td>St.&nbsp;Dev.</td>
<td>1.43</td>
<td>1.6</td>
</tr>
<tr class="odd">
<td>N</td>
<td>50</td>
<td>100</td>
</tr>
</tbody>
</table>
<ol type="a">
<li>What is the estimate of the population difference?</li>
<li>Compute the standard error of the estimate from (a)</li>
</ol>
<hr>
</section>
<section id="question-22-answer" class="level2">
<h2 class="anchored" data-anchor-id="question-22-answer">Question 22: Answer</h2>
<p><strong>22a. Estimate of population difference:</strong></p>
<p><span class="math display">\[\bar{x}_1 - \bar{x}_2 = 6.78 - 7.18 = -0.40 \text{ pounds}\]</span></p>
<p>Babies born to mothers who smoked weighed on average 0.40 pounds less.</p>
<p><strong>22b. Standard error:</strong></p>
<p><span class="math display">\[SE = \sqrt{\frac{s_1^2}{n_1} + \frac{s_2^2}{n_2}}\]</span></p>
<p><span class="math display">\[SE = \sqrt{\frac{1.43^2}{50} + \frac{1.6^2}{100}}\]</span></p>
<p><span class="math display">\[SE = \sqrt{0.0409 + 0.0256} = \sqrt{0.0665} = 0.258 \text{ pounds}\]</span></p>
<hr>
</section>
<section id="question-23a-anova-hypotheses" class="level2">
<h2 class="anchored" data-anchor-id="question-23a-anova-hypotheses">Question 23a: ANOVA Hypotheses</h2>
<p><strong>Question:</strong> College departments offer many lectures of the same course. CSW offers three lectures of an intro stats course to PhD students (A, B, and C). Describe the appropriate hypotheses to determine whether there are any differences between the classes.</p>
<p><strong>Answer:</strong></p>
<p><span class="math inline">\(H_0: \mu_A = \mu_B = \mu_C\)</span></p>
<p>(No difference in mean exam scores across the three classes)</p>
<p><span class="math inline">\(H_1:\)</span> At least one class mean differs from the others</p>
<p>(At least one <span class="math inline">\(\mu_i \neq \mu_j\)</span> for some <span class="math inline">\(i \neq j\)</span>)</p>
<hr>
</section>
<section id="question-23b-anova-results" class="level2">
<h2 class="anchored" data-anchor-id="question-23b-anova-results">Question 23b: ANOVA Results</h2>
<p><strong>Question:</strong> An ANOVA was conducted, and the summary results are below. Is the difference significant at the .05 level? Why or why not?</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Source</th>
<th>Df</th>
<th>Sum Sq</th>
<th>Mean Sq</th>
<th>F-Value</th>
<th>p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Class</td>
<td>2</td>
<td>1290.11</td>
<td>645.06</td>
<td>3.48</td>
<td>.033</td>
</tr>
<tr class="even">
<td>Residuals</td>
<td>161</td>
<td>29810.13</td>
<td>185.16</td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p><strong>Answer:</strong></p>
<p><strong>Yes, the difference is significant at</strong> <span class="math inline">\(\alpha = 0.05\)</span><strong>.</strong></p>
<p>The p-value <span class="math inline">\(= 0.033 &lt; 0.05\)</span>, so we reject the null hypothesis. There is statistically significant evidence that at least one class has a different mean exam score than the others.</p>
<hr>
</section>
<section id="part-ii-applied-analysis-overview" class="level2">
<h2 class="anchored" data-anchor-id="part-ii-applied-analysis-overview">Part II: Applied Analysis Overview</h2>
<p><strong>Requirements:</strong></p>
<p>The applied section requires:</p>
<ol type="a">
<li><p>What is the prevalence of concussion or brain injury in children? (Use appropriate test statistic)</p></li>
<li><p>Are there racial differences in concussion or brain injury? (Use the race variable)</p></li>
<li><p>Are children with concussion/brain injury more likely to bully others? (Compare “not a bully” to categories 2-7)</p></li>
<li><p>Provide a compelling visualization OR interpretation with 1-2 sentences on implications</p></li>
</ol>
<hr>
</section>
<section id="part-ii-analysis-approach" class="level2">
<h2 class="anchored" data-anchor-id="part-ii-analysis-approach">Part II: Analysis Approach</h2>
<p><strong>Data Source:</strong> 2023 National Child Health Survey (NSCH)</p>
<p><strong>Statistical Methods:</strong></p>
<ul>
<li><strong>Prevalence (Q a):</strong> Calculate proportion with 95% CI; one-sample proportion test</li>
<li><strong>Racial differences (Q b):</strong> Chi-square test of independence</li>
<li><strong>Bullying relationship (Q c):</strong> Chi-square test or two-proportion z-test</li>
</ul>
<p><strong>Visualization Options:</strong></p>
<ul>
<li>Bar charts showing prevalence by race</li>
<li>Mosaic plots for categorical relationships</li>
<li>Forest plots for effect sizes across groups</li>
</ul>
<p><strong>Note:</strong> Requires external data download and statistical software (SAS/STATA/R)</p>
<hr>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<p><strong>Key Concepts Covered:</strong></p>
<ul>
<li>Descriptive statistics and probability theory</li>
<li>Independence and conditional probability</li>
<li>Z-scores and normal distributions</li>
<li>Hypothesis testing frameworks (legal analogy)</li>
<li>Confidence intervals and interpretation</li>
<li>t-tests (dependent and independent samples)</li>
<li>ANOVA for comparing multiple groups</li>
<li>Statistical vs.&nbsp;practical significance</li>
<li>Applied data analysis with real-world implications</li>
</ul>
<p><strong>Remember:</strong> Statistics is about choosing the right method for the research question and interpreting findings for policy and social justice implications.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./MTF-solution.html" class="pagination-link" aria-label="Lab 1 - SOLUTION">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Lab 1 - SOLUTION</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->




</body></html>