{
  "hash": "d9f67b37a4389be804ffaed1f617834f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 1: Monitoring the Future\"\nsubtitle: \"Exploring the Association Between Football Participation and Concussion History\"\nauthor: \"Your Name\"\ndate: today\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: show\n    theme: cosmo\n    embed-resources: true\nexecute:\n  warning: false\n  message: false\n---\n\n# Overview\n\nThis analysis examines the relationship between high school football participation and concussion history using data from the **Monitoring the Future (MTF) 2023** survey, a nationally representative study of adolescent behaviors and attitudes. Specifically, we investigate whether students who played competitive football in the past 12 months had higher rates of concussion diagnosis compared to their non-football-playing peers.\n\n::: {.callout-note}\n## Data Source\n**Dataset**: [Monitoring the Future 2024 (ICPSR 39445)](https://www.icpsr.umich.edu/web/NAHDAP/studies/39445/versions/V2/variables)  \n**Sample**: Grade 10 students  \n**Focus**: Relationship between football participation and concussion history\n**R script**: [Click here](monitoring-the-future-example.R) to download the R script for this lab\n:::\n\n# Variable Definitions\n\nThe analysis uses 13 variables from the MTF survey, covering neighborhood safety, school climate, behavioral indicators, sports participation, and demographic characteristics.\n\n## Neighborhood & School Safety\n\n**V8477** - Drug activity in neighborhood  \n*\"During the past 12 months, how often have you seen people selling illegal drugs in your neighborhood?\"*\n\n- 1 = Never\n- 2 = A few times a year\n- 3 = Once or twice a month\n- 4 = At least once a week\n- 5 = Almost every day\n\n**V7535** - Feeling unsafe traveling to/from school  \n*\"How often do you feel unsafe going to or from school?\"*\n\n- 1 = Never\n- 2 = Rarely\n- 3 = Some days\n- 4 = Most days\n- 5 = Every day\n\n**V7536** - School absence due to safety concerns  \n*\"During the last 4 weeks, how many days did you not go to school because you felt unsafe at school or on your way to or from school?\"*\n\n- 1 = 0 days\n- 2 = 1 day\n- 3 = 2 or 3 days\n- 4 = 4 or more days\n\n## Behavioral Indicators\n\n**V8517** - Group fight participation  \n*\"During the last 12 months, how often have you taken part in a group fight where your friends were against another group?\"*\n\n- 1 = Not at all\n- 2 = Once\n- 3 = Twice\n- 4 = 3 or 4 times\n- 5 = 5 or more times\n\n**V8516** - Serious fights at school/work  \n*\"During the last 12 months, how often have you gotten into a serious fight in school or at work?\"*\n\n- 1 = Not at all\n- 2 = Once\n- 3 = Twice\n- 4 = 3 or 4 times\n- 5 = 5 or more times\n\n## Key Variables of Interest\n\n**V7389** - Football participation  \n*\"In which competitive sports (if any) did you participate during the last 12 months?\"*\n\n- 0 = Not marked (did not play football)\n- 1 = Marked (played football)\n\n**V7639** - Concussion history (recoded)  \nOriginal variable recoded into binary format:\n\n- 0 = Never had a concussion\n- 1 = Ever had a concussion (once or multiple times)\n\n## Academic & Demographic Variables\n\n**V7221** - Average grades this school year\n\n- 9 = A (93–100)\n- 8 = A– (90–92)\n- 7 = B+ (87–89)\n- 6 = B (83–86)\n- 5 = B– (80–82)\n- 4 = C+ (77–79)\n- 3 = C (73–76)\n- 2 = C– (70–72)\n- 1 = D (69 or below)\n\n**V1252** - Age classification\n\n- 1 = Younger than 16\n- 2 = 16 years of age or older\n\n**V7202** - Sex\n\n- 1 = Male\n- 2 = Female\n- 3 = Other\n- 4 = Prefer not to answer\n\n**V1070** - Race/ethnicity (recoded)\n\n- 1 = Black or African American\n- 2 = White (Caucasian)\n- 3 = Hispanic\n- Other/multiple responses coded as missing\n\n**V7215** - Father's education level  \n**V7216** - Mother's education level\n\n- 1 = Grade school or less\n- 2 = Some high school\n- 3 = Completed high school\n- 4 = Some college\n- 5 = Completed college\n- 6 = Graduate or professional school\n- 7 = Don't know / Does not apply\n\n# Data Preparation\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Load packages and data\"}\n# Load Required Packages\nlibrary(haven)\nlibrary(dplyr)\n\n# Define variables of interest\nvars <- c(\n  \"V8477\", \"V7535\", \"V7536\", \"V8517\", \"V8516\", \n  \"V7389\", \"V7221\", \"V1252\", \"V7202\", \"V1070\", \n  \"V7215\", \"V7216\", \"V7639\"\n)\n\n# Load the Monitoring the Future dataset\ndf <- read_sav(\"C:/Users/barboza-salerno.1/Downloads/ED injury/ICPSR_39445-V2/ICPSR_39445/DS0001/39445-0001-Data.sav\")\n\n# Select only the variables of interest\ndf <- df %>% \n  dplyr::select(all_of(vars))\n\n# Recode missing values (-8 and -9) to NA\ndf <- df %>% \n  mutate(across(everything(), ~ na_if(.x, -8))) %>% \n  mutate(across(everything(), ~ na_if(.x, -9)))\n```\n:::\n\n\n::: {.callout-tip}\n## Data Cleaning\nMissing value codes (-8 and -9) were recoded to `NA` to ensure proper handling in statistical analyses.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Verify data structure\"}\n# Quick check of data dimensions and summary statistics\ndim(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 17351    13\n```\n\n\n:::\n\n```{.r .cell-code  code-summary=\"Verify data structure\"}\nsummary(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     V8477           V7535           V7536           V8517      \n Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   :1.000  \n 1st Qu.:1.000   1st Qu.:1.000   1st Qu.:1.000   1st Qu.:1.000  \n Median :1.000   Median :1.000   Median :1.000   Median :1.000  \n Mean   :1.323   Mean   :1.588   Mean   :1.196   Mean   :1.191  \n 3rd Qu.:1.000   3rd Qu.:2.000   3rd Qu.:1.000   3rd Qu.:1.000  \n Max.   :5.000   Max.   :5.000   Max.   :4.000   Max.   :5.000  \n NA's   :12404   NA's   :11753   NA's   :11752   NA's   :12700  \n     V8516           V7389           V7221           V1252      \n Min.   :1.000   Min.   :0.000   Min.   :1.000   Min.   :1.000  \n 1st Qu.:1.000   1st Qu.:0.000   1st Qu.:5.000   1st Qu.:1.000  \n Median :1.000   Median :0.000   Median :7.000   Median :2.000  \n Mean   :1.176   Mean   :0.174   Mean   :6.551   Mean   :1.557  \n 3rd Qu.:1.000   3rd Qu.:0.000   3rd Qu.:8.000   3rd Qu.:2.000  \n Max.   :5.000   Max.   :1.000   Max.   :9.000   Max.   :2.000  \n NA's   :12679   NA's   :11831   NA's   :1250    NA's   :8110   \n     V7202           V1070           V7215           V7216      \n Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   :1.000  \n 1st Qu.:1.000   1st Qu.:2.000   1st Qu.:3.000   1st Qu.:3.000  \n Median :2.000   Median :2.000   Median :5.000   Median :5.000  \n Mean   :1.585   Mean   :2.072   Mean   :4.638   Mean   :4.744  \n 3rd Qu.:2.000   3rd Qu.:3.000   3rd Qu.:6.000   3rd Qu.:6.000  \n Max.   :4.000   Max.   :3.000   Max.   :7.000   Max.   :7.000  \n NA's   :1054    NA's   :5042    NA's   :1315    NA's   :1330   \n     V7639      \n Min.   :1.000  \n 1st Qu.:1.000  \n Median :1.000  \n Mean   :1.256  \n 3rd Qu.:1.000  \n Max.   :3.000  \n NA's   :11768  \n```\n\n\n:::\n:::\n\n\n## Creating the Concussion Variable\n\nThe original concussion variable (V7639) was recoded into a binary indicator:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Recode concussion as binary: 0 = No, 1 = Ever had a concussion\ndf$Concussion_Ever <- ifelse(\n  df$V7639 == 1, 0,           # Code 1 = Never → 0\n  ifelse(df$V7639 %in% c(2,3), 1, NA)  # Codes 2,3 = Ever → 1\n)\n\n# Verify recoding\ntable(df$Concussion_Ever, useNA = \"ifany\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n    0     1  <NA> \n 4471  1112 11768 \n```\n\n\n:::\n:::\n\n\n# Exploratory Analysis\n\n## Variable Distributions\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Frequency tables for all variables\"}\n# Generate frequency tables for all variables\nfor (v in names(df)) {\n  cat(\"\\n-----------------------------------------\\n\")\n  cat(\"Variable:\", v, \"\\n\")\n  print(table(df[[v]], useNA = \"ifany\"))\n}\n```\n:::\n\n\n## Key Variables: Football and Concussion\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Football participation\ncat(\"Football Participation (V7389):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFootball Participation (V7389):\n```\n\n\n:::\n\n```{.r .cell-code}\ntable(df$V7389, useNA = \"ifany\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n    0     1  <NA> \n 4559   961 11831 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Concussion history\ncat(\"\\n\\nConcussion History (Recoded):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\nConcussion History (Recoded):\n```\n\n\n:::\n\n```{.r .cell-code}\ntable(df$Concussion_Ever, useNA = \"ifany\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n    0     1  <NA> \n 4471  1112 11768 \n```\n\n\n:::\n:::\n\n\n# Primary Analysis: Football Participation and Concussion Risk\n\n## Cross-Tabulation\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create cross-tabulation\ntab <- table(df$V7389, df$Concussion_Ever)\n\n# Display raw counts\ncat(\"Cross-tabulation (Raw Counts):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCross-tabulation (Raw Counts):\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Rows: Football Participation | Columns: Concussion Ever\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: Football Participation | Columns: Concussion Ever\n```\n\n\n:::\n\n```{.r .cell-code}\ntab\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   \n       0    1\n  0 3733  818\n  1  673  285\n```\n\n\n:::\n\n```{.r .cell-code}\n# Display percentages by row (% within each football participation group)\ncat(\"\\n\\nRow Percentages (% within football participation status):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\nRow Percentages (% within football participation status):\n```\n\n\n:::\n\n```{.r .cell-code}\nround(prop.table(tab, margin = 1) * 100, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   \n        0     1\n  0 82.03 17.97\n  1 70.25 29.75\n```\n\n\n:::\n:::\n\n\n::: {.callout-important}\n## Key Findings from Cross-Tabulation\n\n**Among students who did NOT play football:**  \n818 out of 4,551 (18.0%) reported ever having a concussion\n\n**Among students who DID play football:**  \n285 out of 958 (29.7%) reported ever having a concussion\n\nFootball participants had a **11.7 percentage point higher** rate of concussion history.\n:::\n\n## Statistical Test: Chi-Square Analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Perform chi-square test of independence\nchi_result <- chisq.test(tab)\nchi_result\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test with Yates' continuity correction\n\ndata:  tab\nX-squared = 67.796, df = 1, p-value < 2.2e-16\n```\n\n\n:::\n:::\n\n\n::: {.callout-note}\n## Statistical Significance\nThe chi-square test yielded a highly significant result (p < 0.001), indicating that football participation and concussion history are **not independent**—there is a statistically significant association between playing football and having experienced a concussion.\n:::\n\n## Odds Ratio Calculation\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate odds ratio manually\nodds_football <- tab[2,2] / tab[2,1]      # 285/673\nodds_no_football <- tab[1,2] / tab[1,1]   # 818/3733\n\nodds_ratio <- odds_football / odds_no_football\n\ncat(\"Odds of concussion among football players:\", round(odds_football, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOdds of concussion among football players: 0.423 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Odds of concussion among non-football players:\", round(odds_no_football, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOdds of concussion among non-football players: 0.219 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nOdds Ratio:\", round(odds_ratio, 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nOdds Ratio: 1.93 \n```\n\n\n:::\n:::\n\n\n::: {.callout-warning}\n## Interpretation of Odds Ratio\n\nThe odds ratio of **1.93** indicates that students who reported playing football had approximately **1.9 times the odds** of having been diagnosed with a concussion compared to students who did not play football.\n\nIn simpler terms: **The odds of concussion were nearly twice as high among football participants.**\n:::\n\n# Summary of Results\n\nThis analysis of the Monitoring the Future 2023 dataset reveals a meaningful association between high school football participation and concussion history:\n\n1. **Prevalence**: 29.7% of football players reported concussion history versus 18.0% of non-players\n2. **Statistical significance**: Chi-square test confirmed a significant association (p < 0.001)\n3. **Effect size**: Football players had 1.9 times higher odds of concussion history\n\nThese findings align with existing research on contact sports and head injury risk, suggesting that football participation in adolescence is associated with elevated concussion rates.\n\n# Discussion Questions\n\n::: {.callout-tip icon=false}\n## Question 1: Implications\n\n**What are the potential implications of these findings for school administrators, parents, and student-athletes?**\n\nConsider:\n\n- Should schools modify football programs or safety protocols based on these concussion rates?\n- How might this information influence parental decisions about youth sports participation?\n- What role should medical screening and concussion education play in school athletic programs?\n- Are there policy changes that could help balance the benefits of football participation (teamwork, physical fitness, scholarship opportunities) with injury risk management?\n:::\n\n::: {.callout-tip icon=false}\n## Question 2: Limitations\n\n**What are the key limitations of this analysis, and how might they affect our interpretation of the results?**\n\nConsider:\n\n- **Causality**: Does this cross-sectional design allow us to establish that football *causes* concussions, or only that they're associated?\n- **Self-report bias**: How reliable are student self-reports of concussion diagnosis? Might football players be more aware of concussions or more likely to seek medical attention?\n- **Confounding variables**: What other factors might explain this association (e.g., risk-taking behavior, participation in multiple contact sports, gender composition of football players)?\n- **Temporal ordering**: Did the concussions occur during football, or from other activities?\n- **Severity and recency**: Does this measure distinguish between recent versus historical concussions, or between single versus multiple concussions?\n- **Underreporting**: Might some concussions go undiagnosed, particularly in students without access to medical care?\n:::\n\n# Student Exercise: Analyze School Safety and Attendance\n\n::: {.callout-important icon=false}\n## Your Task\n\nNow it's your turn! Using the analytical approach demonstrated in the football-concussion example, examine the following research question:\n\n**Research Question:** *Do students who feel unsafe going to/from school have higher rates of school absence due to safety concerns?*\n\n**Variables to Use:**\n\n- **V7535** - How often do you feel unsafe going to or from school?\n  - 1 = Never, 2 = Rarely, 3 = Some days, 4 = Most days, 5 = Every day\n  \n- **V7536** - During the last 4 weeks, how many days did you not go to school because you felt unsafe?\n  - 1 = 0 days, 2 = 1 day, 3 = 2 or 3 days, 4 = 4 or more days\n\n**Instructions:**\n\n1. **Recode both variables into binary format:**\n   - Create `Feel_Unsafe`: 0 = Never feel unsafe, 1 = Ever feel unsafe (any response other than \"Never\")\n   - Create `Absent_Safety`: 0 = No days missed, 1 = Any days missed due to safety\n\n2. **Generate a cross-tabulation** showing:\n   - Raw counts\n   - Row percentages (percentage within each \"feeling unsafe\" category)\n\n3. **Perform a chi-square test** to determine if the association is statistically significant\n\n4. **Calculate the odds ratio** and interpret it clearly:\n   - Show the odds of absence for students who feel unsafe\n   - Show the odds of absence for students who never feel unsafe\n   - Calculate the ratio and explain what it means in plain language\n\n5. **Write a brief interpretation** that includes:\n   - The strength and direction of the association\n   - Statistical significance\n   - Practical implications of your findings\n\n**Hints:**\n\n- Use the `ifelse()` function to recode variables (follow the concussion recoding example)\n- Here's how to recode V7535 (Feeling Unsafe) step-by-step:\n\n```r\n# Original variable V7535: 1=Never, 2=Rarely, 3=Some days, 4=Most days, 5=Every day\n# Goal: Create binary variable where 0=Never, 1=Ever feel unsafe\n\ndf$Feel_Unsafe <- ifelse(\n  df$V7535 == 1,                      # Condition: if V7535 equals 1\n  0,                                   # Then: assign 0 (Never feel unsafe)\n  ifelse(df$V7535 %in% c(2,3,4,5),    # Else if: V7535 is 2, 3, 4, or 5\n         1,                            # Then: assign 1 (Ever feel unsafe)\n         NA)                           # Else: assign NA (missing)\n)\n```\n- Now try the same approach for V7536 (School Absence):\n  - Original: 1=0 days, 2=1 day, 3=2-3 days, 4=4+ days\n  - Create `Absent_Safety`: 0=No days missed (V7536==1), 1=Any days missed (V7536 in 2,3,4)\n\n- Remember the 2×2 table structure for odds ratios:\n  ```\n                 Absent=0  Absent=1\n  Feel_Unsafe=0     a         b\n  Feel_Unsafe=1     c         d\n  \n  Odds Ratio = (d/c) / (b/a)\n  ```\n- Make sure to handle missing values appropriately\n\nGood luck with your analysis! Compare your results with your classmates to see if you obtained the same findings. Then, you can [click here](MTF-solution.qmd) to look at my solution.\n\n**Document created**: 2026-01-27",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}